In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (20,10)

In [2]:
# download csv from url
url = 'https://archives.nseindia.com/content/indices/ind_nifty100list.csv' # Nifty 100 stocks
nifty100 = pd.read_csv(url)
nifty100= nifty100.to_csv('ind_nifty100list.csv', index=False)

symbol= pd.read_csv("ind_nifty100list.csv")  # read csv file
symbol["ticker"] = symbol["Symbol"] + ".NS"
ticker= symbol['ticker'].values.tolist() # convert to list
sd = yf.download(ticker, interval='1d')['Close'] # download data from yahoo finance

[*********************100%***********************]  100 of 100 completed

In [3]:
sd

,ABB.NS,ADANIENSOL.NS,ADANIENT.NS,ADANIGREEN.NS,ADANIPORTS.NS,ADANIPOWER.NS,AMBUJACEM.NS,APOLLOHOSP.NS,ASIANPAINT.NS,ATGL.NS,...,TRENT.NS,TVSMOTOR.NS,ULTRACEMCO.NS,UNIONBANK.NS,UNITDSPR.NS,VBL.NS,VEDL.NS,WIPRO.NS,ZOMATO.NS,ZYDUSLIFE.NS
Date,,,,,,,,,,,,,,,,,,,,,
1991-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-09-27,8133.450195,1010.200012,3130.300049,1981.849976,1456.699951,654.299988,634.000000,7234.000000,3310.750000,783.750000,...,7833.700195,2949.699951,11952.299805,123.510002,1596.599976,608.549988,513.000000,541.799988,278.149994,1075.949951
2024-09-30,8055.000000,1009.650024,3135.850098,1902.699951,1448.199951,656.150024,632.549988,7199.149902,3329.100098,786.500000,...,7574.649902,2839.850098,11802.000000,122.769997,1589.900024,606.299988,512.650024,541.450012,273.299988,1068.550049
2024-10-01,8268.099609,1040.099976,3186.100098,1884.949951,1467.500000,653.200012,632.450012,7153.350098,3277.350098,786.450012,...,7612.700195,2838.649902,11837.150391,121.860001,1610.949951,612.250000,516.150024,546.750000,274.149994,1080.349976
2024-10-03,8110.299805,1015.849976,3116.000000,1807.800049,1425.199951,644.750000,617.450012,6905.950195,3149.300049,772.250000,...,7487.899902,2725.600098,11724.799805,118.980003,1564.099976,587.750000,511.750000,530.150024,269.000000,1069.050049
2024-10-04,7930.399902,962.750000,3110.649902,1801.199951,1413.699951,642.099976,610.700012,6773.600098,3072.500000,763.400024,...,7353.299805,2687.500000,11450.250000,118.860001,1531.349976,578.900024,508.700012,533.549988,275.299988,1057.349976

In [17]:
current_date = (pd.to_datetime('today') - pd.Timedelta(days=1500)).strftime('%Y-%m-%d')  # 1460 days = 4 years
sd1 = sd[sd.index > current_date] # filter data for last 4 years
#drop columns with all NaN values
sd1.dropna(axis=1, how='any', inplace=True)
sd1_columns =sd1.columns # get column names
sd1

,ABB.NS,ADANIENT.NS,ADANIGREEN.NS,ADANIPORTS.NS,ADANIPOWER.NS,AMBUJACEM.NS,APOLLOHOSP.NS,ASIANPAINT.NS,ATGL.NS,AXISBANK.NS,...,TITAN.NS,TORNTPHARM.NS,TRENT.NS,TVSMOTOR.NS,ULTRACEMCO.NS,UNIONBANK.NS,VBL.NS,VEDL.NS,WIPRO.NS,ZYDUSLIFE.NS
Date,,,,,,,,,,,,,,,,,,,,,
2020-08-28,985.599976,288.250000,462.299988,360.049988,39.250000,222.449997,1661.949951,1958.099976,186.550003,509.200012,...,1134.099976,1354.724976,650.450012,449.750000,4062.550049,31.400000,67.044441,128.850006,272.049988,388.850006
2020-08-31,950.750000,279.549988,452.750000,355.750000,37.250000,210.550003,1634.550049,1899.099976,169.750000,496.750000,...,1100.500000,1330.800049,639.200012,432.850006,3903.850098,30.200001,65.422218,128.649994,271.299988,371.250000
2020-09-01,945.599976,281.100006,494.649994,348.799988,38.799999,213.000000,1670.849976,1979.300049,177.199997,485.700012,...,1120.050049,1354.925049,638.549988,440.399994,3912.649902,29.900000,67.897774,132.000000,271.600006,378.100006
2020-09-02,974.750000,293.049988,544.099976,359.899994,39.150002,217.250000,1698.650024,1943.949951,189.949997,484.399994,...,1121.300049,1380.900024,651.750000,437.100006,3941.699951,29.600000,68.115555,131.100006,273.700012,382.000000
2020-09-03,981.349976,291.250000,571.299988,366.000000,38.650002,214.600006,1698.949951,1978.000000,189.850006,474.950012,...,1185.300049,1398.724976,651.799988,435.350006,3949.000000,29.750000,66.724442,128.500000,282.850006,387.049988
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-09-27,8133.450195,3130.300049,1981.849976,1456.699951,654.299988,634.000000,7234.000000,3310.750000,783.750000,1273.150024,...,3816.699951,3482.600098,7833.700195,2949.699951,11952.299805,123.510002,608.549988,513.000000,541.799988,1075.949951
2024-09-30,8055.000000,3135.850098,1902.699951,1448.199951,656.150024,632.549988,7199.149902,3329.100098,786.500000,1232.199951,...,3823.949951,3396.550049,7574.649902,2839.850098,11802.000000,122.769997,606.299988,512.650024,541.450012,1068.550049
2024-10-01,8268.099609,3186.100098,1884.949951,1467.500000,653.200012,632.450012,7153.350098,3277.350098,786.450012,1226.650024,...,3775.949951,3369.899902,7612.700195,2838.649902,11837.150391,121.860001,612.250000,516.150024,546.750000,1080.349976
2024-10-03,8110.299805,3116.000000,1807.800049,1425.199951,644.750000,617.450012,6905.950195,3149.300049,772.250000,1175.699951,...,3674.949951,3392.149902,7487.899902,2725.600098,11724.799805,118.980003,587.750000,511.750000,530.150024,1069.050049
2024-10-04,7930.399902,3110.649902,1801.199951,1413.699951,642.099976,610.700012,6773.600098,3072.500000,763.400024,1178.400024,...,3670.100098,3473.550049,7353.299805,2687.500000,11450.250000,118.860001,578.900024,508.700012,533.549988,1057.349976

In [34]:
returns = sd1.pct_change()
returns.dropna(axis=1, how='any', inplace=True)
returns.tail()
returns

Empty DataFrame
Columns: []
Index: [2020-08-28 00:00:00, 2020-08-31 00:00:00, 2020-09-01 00:00:00, 2020-09-02 00:00:00, 2020-09-03 00:00:00, 2020-09-04 00:00:00, 2020-09-07 00:00:00, 2020-09-08 00:00:00, 2020-09-09 00:00:00, 2020-09-10 00:00:00, 2020-09-11 00:00:00, 2020-09-14 00:00:00, 2020-09-15 00:00:00, 2020-09-16 00:00:00, 2020-09-17 00:00:00, 2020-09-18 00:00:00, 2020-09-21 00:00:00, 2020-09-22 00:00:00, 2020-09-23 00:00:00, 2020-09-24 00:00:00, 2020-09-25 00:00:00, 2020-09-28 00:00:00, 2020-09-29 00:00:00, 2020-09-30 00:00:00, 2020-10-01 00:00:00, 2020-10-05 00:00:00, 2020-10-06 00:00:00, 2020-10-07 00:00:00, 2020-10-08 00:00:00, 2020-10-09 00:00:00, 2020-10-12 00:00:00, 2020-10-13 00:00:00, 2020-10-14 00:00:00, 2020-10-15 00:00:00, 2020-10-16 00:00:00, 2020-10-19 00:00:00, 2020-10-20 00:00:00, 2020-10-21 00:00:00, 2020-10-22 00:00:00, 2020-10-23 00:00:00, 2020-10-26 00:00:00, 2020-10-27 00:00:00, 2020-10-28 00:00:00, 2020-10-29 00:00:00, 2020-10-30 00:00:00, 2020-11-02 00:00:00, 2020-11-03 00:00:00, 2020-11-04 00:00:00, 2020-11-05 00:00:00, 2020-11-06 00:00:00, 2020-11-09 00:00:00, 2020-11-10 00:00:00, 2020-11-11 00:00:00, 2020-11-12 00:00:00, 2020-11-13 00:00:00, 2020-11-14 00:00:00, 2020-11-17 00:00:00, 2020-11-18 00:00:00, 2020-11-19 00:00:00, 2020-11-20 00:00:00, 2020-11-23 00:00:00, 2020-11-24 00:00:00, 2020-11-25 00:00:00, 2020-11-26 00:00:00, 2020-11-27 00:00:00, 2020-12-01 00:00:00, 2020-12-02 00:00:00, 2020-12-03 00:00:00, 2020-12-04 00:00:00, 2020-12-07 00:00:00, 2020-12-08 00:00:00, 2020-12-09 00:00:00, 2020-12-10 00:00:00, 2020-12-11 00:00:00, 2020-12-14 00:00:00, 2020-12-15 00:00:00, 2020-12-16 00:00:00, 2020-12-17 00:00:00, 2020-12-18 00:00:00, 2020-12-21 00:00:00, 2020-12-22 00:00:00, 2020-12-23 00:00:00, 2020-12-24 00:00:00, 2020-12-28 00:00:00, 2020-12-29 00:00:00, 2020-12-30 00:00:00, 2020-12-31 00:00:00, 2021-01-01 00:00:00, 2021-01-04 00:00:00, 2021-01-05 00:00:00, 2021-01-06 00:00:00, 2021-01-07 00:00:00, 2021-01-08 00:00:00, 2021-01-11 00:00:00, 2021-01-12 00:00:00, 2021-01-13 00:00:00, 2021-01-14 00:00:00, 2021-01-15 00:00:00, 2021-01-18 00:00:00, 2021-01-19 00:00:00, ...]

[1015 rows x 0 columns]

In [5]:
sd1.to_csv("prices.csv")

In [18]:
sd1

,ABB.NS,ADANIENT.NS,ADANIGREEN.NS,ADANIPORTS.NS,ADANIPOWER.NS,AMBUJACEM.NS,APOLLOHOSP.NS,ASIANPAINT.NS,ATGL.NS,AXISBANK.NS,...,TITAN.NS,TORNTPHARM.NS,TRENT.NS,TVSMOTOR.NS,ULTRACEMCO.NS,UNIONBANK.NS,VBL.NS,VEDL.NS,WIPRO.NS,ZYDUSLIFE.NS
Date,,,,,,,,,,,,,,,,,,,,,
2020-08-28,985.599976,288.250000,462.299988,360.049988,39.250000,222.449997,1661.949951,1958.099976,186.550003,509.200012,...,1134.099976,1354.724976,650.450012,449.750000,4062.550049,31.400000,67.044441,128.850006,272.049988,388.850006
2020-08-31,950.750000,279.549988,452.750000,355.750000,37.250000,210.550003,1634.550049,1899.099976,169.750000,496.750000,...,1100.500000,1330.800049,639.200012,432.850006,3903.850098,30.200001,65.422218,128.649994,271.299988,371.250000
2020-09-01,945.599976,281.100006,494.649994,348.799988,38.799999,213.000000,1670.849976,1979.300049,177.199997,485.700012,...,1120.050049,1354.925049,638.549988,440.399994,3912.649902,29.900000,67.897774,132.000000,271.600006,378.100006
2020-09-02,974.750000,293.049988,544.099976,359.899994,39.150002,217.250000,1698.650024,1943.949951,189.949997,484.399994,...,1121.300049,1380.900024,651.750000,437.100006,3941.699951,29.600000,68.115555,131.100006,273.700012,382.000000
2020-09-03,981.349976,291.250000,571.299988,366.000000,38.650002,214.600006,1698.949951,1978.000000,189.850006,474.950012,...,1185.300049,1398.724976,651.799988,435.350006,3949.000000,29.750000,66.724442,128.500000,282.850006,387.049988
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-09-27,8133.450195,3130.300049,1981.849976,1456.699951,654.299988,634.000000,7234.000000,3310.750000,783.750000,1273.150024,...,3816.699951,3482.600098,7833.700195,2949.699951,11952.299805,123.510002,608.549988,513.000000,541.799988,1075.949951
2024-09-30,8055.000000,3135.850098,1902.699951,1448.199951,656.150024,632.549988,7199.149902,3329.100098,786.500000,1232.199951,...,3823.949951,3396.550049,7574.649902,2839.850098,11802.000000,122.769997,606.299988,512.650024,541.450012,1068.550049
2024-10-01,8268.099609,3186.100098,1884.949951,1467.500000,653.200012,632.450012,7153.350098,3277.350098,786.450012,1226.650024,...,3775.949951,3369.899902,7612.700195,2838.649902,11837.150391,121.860001,612.250000,516.150024,546.750000,1080.349976
2024-10-03,8110.299805,3116.000000,1807.800049,1425.199951,644.750000,617.450012,6905.950195,3149.300049,772.250000,1175.699951,...,3674.949951,3392.149902,7487.899902,2725.600098,11724.799805,118.980003,587.750000,511.750000,530.150024,1069.050049
2024-10-04,7930.399902,3110.649902,1801.199951,1413.699951,642.099976,610.700012,6773.600098,3072.500000,763.400024,1178.400024,...,3670.100098,3473.550049,7353.299805,2687.500000,11450.250000,118.860001,578.900024,508.700012,533.549988,1057.349976

In [13]:
def returns(df): # function to calculate momentum ratio
    for i in df.columns:
        ret_daily = df[i].pct_change(periods=1) # percent change over daily trading days
        stdev_5 = ret_daily.rolling(window=5).std() # standard deviation over 5 trading days
        avg_ret = ret_daily.rolling(window=5).median()
        df[i+'_ret']=df[i].pct_change(periods=1)
        df[i+'_Year_momentum'] = avg_ret / stdev_5 
        df.dropna(inplace=True) # drop rows with NaN values
    returns df
returns_df=return(df)
#momentum_df = momentum_ratio(sd1)

SyntaxError: invalid syntax (2957374520.py, line 9)

In [10]:
sd1

,ABB.NS,ADANIENT.NS,ADANIGREEN.NS,ADANIPORTS.NS,ADANIPOWER.NS,AMBUJACEM.NS,APOLLOHOSP.NS,ASIANPAINT.NS,ATGL.NS,AXISBANK.NS,...,TITAN.NS,TORNTPHARM.NS,TRENT.NS,TVSMOTOR.NS,ULTRACEMCO.NS,UNIONBANK.NS,VBL.NS,VEDL.NS,WIPRO.NS,ZYDUSLIFE.NS
Date,,,,,,,,,,,,,,,,,,,,,
2020-08-28,985.599976,288.250000,462.299988,360.049988,39.250000,222.449997,1661.949951,1958.099976,186.550003,509.200012,...,1134.099976,1354.724976,650.450012,449.750000,4062.550049,31.400000,67.044441,128.850006,272.049988,388.850006
2020-08-31,950.750000,279.549988,452.750000,355.750000,37.250000,210.550003,1634.550049,1899.099976,169.750000,496.750000,...,1100.500000,1330.800049,639.200012,432.850006,3903.850098,30.200001,65.422218,128.649994,271.299988,371.250000
2020-09-01,945.599976,281.100006,494.649994,348.799988,38.799999,213.000000,1670.849976,1979.300049,177.199997,485.700012,...,1120.050049,1354.925049,638.549988,440.399994,3912.649902,29.900000,67.897774,132.000000,271.600006,378.100006
2020-09-02,974.750000,293.049988,544.099976,359.899994,39.150002,217.250000,1698.650024,1943.949951,189.949997,484.399994,...,1121.300049,1380.900024,651.750000,437.100006,3941.699951,29.600000,68.115555,131.100006,273.700012,382.000000
2020-09-03,981.349976,291.250000,571.299988,366.000000,38.650002,214.600006,1698.949951,1978.000000,189.850006,474.950012,...,1185.300049,1398.724976,651.799988,435.350006,3949.000000,29.750000,66.724442,128.500000,282.850006,387.049988
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-09-27,8133.450195,3130.300049,1981.849976,1456.699951,654.299988,634.000000,7234.000000,3310.750000,783.750000,1273.150024,...,3816.699951,3482.600098,7833.700195,2949.699951,11952.299805,123.510002,608.549988,513.000000,541.799988,1075.949951
2024-09-30,8055.000000,3135.850098,1902.699951,1448.199951,656.150024,632.549988,7199.149902,3329.100098,786.500000,1232.199951,...,3823.949951,3396.550049,7574.649902,2839.850098,11802.000000,122.769997,606.299988,512.650024,541.450012,1068.550049
2024-10-01,8268.099609,3186.100098,1884.949951,1467.500000,653.200012,632.450012,7153.350098,3277.350098,786.450012,1226.650024,...,3775.949951,3369.899902,7612.700195,2838.649902,11837.150391,121.860001,612.250000,516.150024,546.750000,1080.349976
2024-10-03,8110.299805,3116.000000,1807.800049,1425.199951,644.750000,617.450012,6905.950195,3149.300049,772.250000,1175.699951,...,3674.949951,3392.149902,7487.899902,2725.600098,11724.799805,118.980003,587.750000,511.750000,530.150024,1069.050049
2024-10-04,7930.399902,3110.649902,1801.199951,1413.699951,642.099976,610.700012,6773.600098,3072.500000,763.400024,1178.400024,...,3670.100098,3473.550049,7353.299805,2687.500000,11450.250000,118.860001,578.900024,508.700012,533.549988,1057.349976

In [8]:
def Calculate_Z_Score(df,columns=sd1_columns):
    for i in columns:  # calculate z score for each stock
        mean252 = df[i+'_Year_momentum'].rolling(window=252).mean() # mean over 252 trading days
        std252 = df[i+'_Year_momentum'].rolling(window=252).std() # standard deviation over 252 trading days
        df[i+'Year_Z_Score'] = (df[i]-mean252)/std252 # z score for 252 trading days
        mean126 = df[i+'_6_month_momentum'].rolling(window=126).mean() # mean over 126 trading days
        std126 = df[i+'_6_month_momentum'].rolling(window=126).std() # standard deviation over 126 trading days
        df[i+'6_month_Z_Score'] = (df[i]-mean126)/std126 # z score for 126 trading days
        df[i+'ALL_Z_Score'] = (df[i+'Year_Z_Score'] + df[i+'6_month_Z_Score'])/2 # average z score (weighted average)
    df.dropna(inplace=True) # drop rows with NaN values
    return df
momentum_df = Calculate_Z_Score(momentum_df) # calculate z score
momentum_df

KeyError: 'ABB.NS_6_month_momentum'

In [8]:
momentum_df.to_csv("momentum11.csv")

In [9]:
def Calculate_Z_Score(df,columns=sd1_columns):
       for i in columns:  # calculate z score for each stock
            momentum = df[i+'_Year_momentum'].rolling(window=252).mean() # mean over 252 trading days
            mean252 = df[i+'_Year_momentum'].rolling(window=252).mean() # mean over 252 trading days
            std252 = df[i+'_Year_momentum'].rolling(window=252).std() # standard deviation over 252 trading days
            df[i+'Year_Z_Score'] = (df[i]-mean252)/std252 # z score for 252 trading days
            df.dropna(inplace=True) # drop rows with NaN values
            return df
momentum_df = Calculate_Z_Score(momentum_df) # calculate z score
momentum_df

,ABB.NS,ADANIENT.NS,ADANIGREEN.NS,ADANIPORTS.NS,ADANIPOWER.NS,AMBUJACEM.NS,APOLLOHOSP.NS,ASIANPAINT.NS,ATGL.NS,AXISBANK.NS,...,TITAN.NS_Year_momentum,TORNTPHARM.NS_Year_momentum,TRENT.NS_Year_momentum,TVSMOTOR.NS_Year_momentum,ULTRACEMCO.NS_Year_momentum,VBL.NS_Year_momentum,VEDL.NS_Year_momentum,WIPRO.NS_Year_momentum,ZYDUSLIFE.NS_Year_momentum,ABB.NSYear_Z_Score
Date,,,,,,,,,,,,,,,,,,,,,
2023-07-14,4383.799805,2376.100098,965.200012,726.099976,241.899994,416.600006,5171.799805,3429.750000,633.900024,957.049988,...,-0.225968,0.632370,-0.233704,-0.204276,-0.504672,0.000000,0.097953,0.354423,0.790004,8980.922062
2023-07-17,4418.950195,2408.550049,965.299988,731.049988,245.699997,416.600006,5219.299805,3460.399902,647.000000,964.849976,...,-0.404297,0.021498,0.377702,-0.215422,-0.383381,0.000000,0.024258,0.495267,0.930650,9073.878234
2023-07-18,4490.850098,2416.899902,973.750000,728.150024,246.550003,416.200012,5162.600098,3513.449951,645.750000,963.650024,...,-1.241809,-0.207329,-0.246225,-0.342613,-0.734007,-0.398242,0.028413,0.491244,0.806367,9222.346573
2023-07-19,4493.500000,2423.750000,979.650024,731.400024,245.699997,419.299988,5175.600098,3514.649902,641.150024,964.299988,...,-1.542727,-0.227563,0.339031,-0.569882,0.145510,-1.372721,0.112970,0.514017,0.945551,9227.935135
2023-07-20,4204.000000,2419.750000,985.000000,732.450012,244.149994,420.899994,5195.450195,3526.000000,640.049988,977.900024,...,-1.449935,-0.217966,0.487383,0.235469,-0.471778,-1.621910,-0.261129,0.348740,1.309022,8638.749789
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-09-20,7695.750000,3008.500000,2003.949951,1438.699951,665.150024,616.549988,7082.649902,3306.949951,788.700012,1245.000000,...,0.404147,-0.009027,1.019422,-0.446399,-0.037045,0.115130,0.046953,0.000000,-0.335727,12999.320807
2024-09-23,7939.649902,3043.949951,2031.199951,1456.150024,672.000000,622.049988,7152.799805,3277.449951,835.349976,1246.800049,...,0.633022,-0.009027,0.882404,-0.411236,0.031871,0.172875,0.696912,-0.594498,-0.321214,13423.924138
2024-09-24,8078.200195,3093.899902,2070.550049,1456.650024,675.250000,618.299988,7122.000000,3248.399902,812.950012,1239.550049,...,0.391396,-0.002078,-0.020518,0.704388,-0.022594,-0.071524,0.196067,-0.532986,-0.254377,13642.074022
2024-09-25,8178.350098,3105.100098,2066.750000,1452.550049,667.349976,616.049988,7133.450195,3244.750000,801.099976,1268.099976,...,0.377452,-0.002637,-0.023983,0.990325,0.362148,-0.045186,0.453186,-0.647115,0.011135,13814.579092
2024-09-26,8070.399902,3122.649902,2057.850098,1472.599976,665.349976,625.150024,7167.850098,3277.050049,792.099976,1277.099976,...,0.480183,-0.002597,1.371538,1.486816,0.939876,-1.058389,1.060524,0.926463,0.109799,13576.995228

In [10]:
winners = pd.DataFrame(columns=['W1','W2','W3','W4','W5','W6','W7','W8','W9','W10'])
loosers = pd.DataFrame(columns=['L1','L2','L3','L4','L5','L6','L7','L8','L9','L10'])

In [11]:
m1=momentum_df.to_csv('momentum1.csv')
momentum_df

,ABB.NS,ADANIENT.NS,ADANIGREEN.NS,ADANIPORTS.NS,ADANIPOWER.NS,AMBUJACEM.NS,APOLLOHOSP.NS,ASIANPAINT.NS,ATGL.NS,AXISBANK.NS,...,TITAN.NS_Year_momentum,TORNTPHARM.NS_Year_momentum,TRENT.NS_Year_momentum,TVSMOTOR.NS_Year_momentum,ULTRACEMCO.NS_Year_momentum,VBL.NS_Year_momentum,VEDL.NS_Year_momentum,WIPRO.NS_Year_momentum,ZYDUSLIFE.NS_Year_momentum,ABB.NSYear_Z_Score
Date,,,,,,,,,,,,,,,,,,,,,
2023-07-14,4383.799805,2376.100098,965.200012,726.099976,241.899994,416.600006,5171.799805,3429.750000,633.900024,957.049988,...,-0.225968,0.632370,-0.233704,-0.204276,-0.504672,0.000000,0.097953,0.354423,0.790004,8980.922062
2023-07-17,4418.950195,2408.550049,965.299988,731.049988,245.699997,416.600006,5219.299805,3460.399902,647.000000,964.849976,...,-0.404297,0.021498,0.377702,-0.215422,-0.383381,0.000000,0.024258,0.495267,0.930650,9073.878234
2023-07-18,4490.850098,2416.899902,973.750000,728.150024,246.550003,416.200012,5162.600098,3513.449951,645.750000,963.650024,...,-1.241809,-0.207329,-0.246225,-0.342613,-0.734007,-0.398242,0.028413,0.491244,0.806367,9222.346573
2023-07-19,4493.500000,2423.750000,979.650024,731.400024,245.699997,419.299988,5175.600098,3514.649902,641.150024,964.299988,...,-1.542727,-0.227563,0.339031,-0.569882,0.145510,-1.372721,0.112970,0.514017,0.945551,9227.935135
2023-07-20,4204.000000,2419.750000,985.000000,732.450012,244.149994,420.899994,5195.450195,3526.000000,640.049988,977.900024,...,-1.449935,-0.217966,0.487383,0.235469,-0.471778,-1.621910,-0.261129,0.348740,1.309022,8638.749789
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-09-20,7695.750000,3008.500000,2003.949951,1438.699951,665.150024,616.549988,7082.649902,3306.949951,788.700012,1245.000000,...,0.404147,-0.009027,1.019422,-0.446399,-0.037045,0.115130,0.046953,0.000000,-0.335727,12999.320807
2024-09-23,7939.649902,3043.949951,2031.199951,1456.150024,672.000000,622.049988,7152.799805,3277.449951,835.349976,1246.800049,...,0.633022,-0.009027,0.882404,-0.411236,0.031871,0.172875,0.696912,-0.594498,-0.321214,13423.924138
2024-09-24,8078.200195,3093.899902,2070.550049,1456.650024,675.250000,618.299988,7122.000000,3248.399902,812.950012,1239.550049,...,0.391396,-0.002078,-0.020518,0.704388,-0.022594,-0.071524,0.196067,-0.532986,-0.254377,13642.074022
2024-09-25,8178.350098,3105.100098,2066.750000,1452.550049,667.349976,616.049988,7133.450195,3244.750000,801.099976,1268.099976,...,0.377452,-0.002637,-0.023983,0.990325,0.362148,-0.045186,0.453186,-0.647115,0.011135,13814.579092
2024-09-26,8070.399902,3122.649902,2057.850098,1472.599976,665.349976,625.150024,7167.850098,3277.050049,792.099976,1277.099976,...,0.480183,-0.002597,1.371538,1.486816,0.939876,-1.058389,1.060524,0.926463,0.109799,13576.995228

In [28]:
#get top 10 maximum values column name in winners
#get colums containing 'Year_momentum' in momentum_df
#momentum_df = momentum_df.filter(regex='NS_Year_momentum')
momentum_df
#for i in momentum_df.index:
    #winners.loc[i] = momentum_df.loc[i].nlargest(10).index.tolist()
    #loosers.loc[i] = momentum_df.loc[i].nsmallest(10).index.tolist()

Empty DataFrame
Columns: []
Index: [2023-06-05 00:00:00, 2023-06-06 00:00:00, 2023-06-07 00:00:00, 2023-06-08 00:00:00, 2023-06-09 00:00:00, 2023-06-12 00:00:00, 2023-06-13 00:00:00, 2023-06-14 00:00:00, 2023-06-15 00:00:00, 2023-06-16 00:00:00, 2023-06-19 00:00:00, 2023-06-20 00:00:00, 2023-06-21 00:00:00, 2023-06-22 00:00:00, 2023-06-23 00:00:00, 2023-06-26 00:00:00, 2023-06-27 00:00:00, 2023-06-28 00:00:00, 2023-06-30 00:00:00, 2023-07-03 00:00:00, 2023-07-04 00:00:00, 2023-07-05 00:00:00, 2023-07-06 00:00:00, 2023-07-07 00:00:00, 2023-07-10 00:00:00, 2023-07-11 00:00:00, 2023-07-12 00:00:00, 2023-07-13 00:00:00, 2023-07-14 00:00:00, 2023-07-17 00:00:00, 2023-07-18 00:00:00, 2023-07-19 00:00:00, 2023-07-20 00:00:00, 2023-07-21 00:00:00, 2023-07-24 00:00:00, 2023-07-25 00:00:00, 2023-07-26 00:00:00, 2023-07-27 00:00:00, 2023-07-28 00:00:00, 2023-07-31 00:00:00, 2023-08-01 00:00:00, 2023-08-02 00:00:00, 2023-08-03 00:00:00, 2023-08-04 00:00:00, 2023-08-07 00:00:00, 2023-08-08 00:00:00, 2023-08-09 00:00:00, 2023-08-10 00:00:00, 2023-08-11 00:00:00, 2023-08-14 00:00:00, 2023-08-16 00:00:00, 2023-08-17 00:00:00, 2023-08-18 00:00:00, 2023-08-21 00:00:00, 2023-08-22 00:00:00, 2023-08-23 00:00:00, 2023-08-24 00:00:00, 2023-08-25 00:00:00, 2023-08-28 00:00:00, 2023-08-29 00:00:00, 2023-08-30 00:00:00, 2023-08-31 00:00:00, 2023-09-01 00:00:00, 2023-09-04 00:00:00, 2023-09-05 00:00:00, 2023-09-06 00:00:00, 2023-09-07 00:00:00, 2023-09-08 00:00:00, 2023-09-11 00:00:00, 2023-09-12 00:00:00, 2023-09-13 00:00:00, 2023-09-14 00:00:00, 2023-09-15 00:00:00, 2023-09-18 00:00:00, 2023-09-20 00:00:00, 2023-09-21 00:00:00, 2023-09-22 00:00:00, 2023-09-25 00:00:00, 2023-09-26 00:00:00, 2023-09-27 00:00:00, 2023-09-28 00:00:00, 2023-09-29 00:00:00, 2023-10-03 00:00:00, 2023-10-04 00:00:00, 2023-10-05 00:00:00, 2023-10-06 00:00:00, 2023-10-09 00:00:00, 2023-10-10 00:00:00, 2023-10-11 00:00:00, 2023-10-12 00:00:00, 2023-10-13 00:00:00, 2023-10-16 00:00:00, 2023-10-17 00:00:00, 2023-10-18 00:00:00, 2023-10-19 00:00:00, 2023-10-20 00:00:00, 2023-10-23 00:00:00, 2023-10-25 00:00:00, 2023-10-26 00:00:00, 2023-10-27 00:00:00, ...]

[291 rows x 0 columns]

In [29]:
winners

In [31]:
loosers

Empty DataFrame
Columns: [L1, L2, L3, L4, L5, L6, L7, L8, L9, L10]
Index: []

In [32]:
winners.to_csv('winners.csv', index=False)
loosers.to_csv('loosers.csv', index=False)