In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (20,10)

In [12]:
# download csv from url
url = 'https://archives.nseindia.com/content/indices/ind_nifty100list.csv' # Nifty 100 stocks
nifty100 = pd.read_csv(url)
nifty100= nifty100.to_csv('ind_nifty100list.csv', index=False)

symbol= pd.read_csv("ind_nifty100list.csv")  # read csv file
symbol["ticker"] = symbol["Symbol"] + ".NS"
ticker= symbol['ticker'].values.tolist() # convert to list
sd = yf.download(ticker, interval='1d')['Close'] # download data from yahoo finance

[*********************100%***********************]  101 of 101 completed

,ABB.NS,ADANIENSOL.NS,ADANIENT.NS,ADANIGREEN.NS,ADANIPORTS.NS,ADANIPOWER.NS,AMBUJACEM.NS,APOLLOHOSP.NS,ASIANPAINT.NS,ATGL.NS,...,TORNTPHARM.NS,TRENT.NS,TVSMOTOR.NS,ULTRACEMCO.NS,UNITDSPR.NS,VBL.NS,VEDL.NS,WIPRO.NS,ZOMATO.NS,ZYDUSLIFE.NS
Date,,,,,,,,,,,,,,,,,,,,,
1991-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08-05,7465.700195,1159.099976,3038.199951,1768.750000,1493.849976,690.849976,636.150024,6687.600098,3093.399902,857.049988,...,3167.500000,5346.899902,2493.350098,11417.250000,1400.250000,1504.750000,413.250000,485.000000,256.290009,1227.550049
2024-08-06,7465.700195,1124.849976,3072.699951,1749.599976,1494.099976,689.400024,625.549988,6657.700195,3101.750000,868.099976,...,3220.550049,5220.700195,2478.800049,11325.299805,1411.099976,1461.949951,413.899994,489.500000,249.080002,1227.699951
2024-08-07,7870.399902,1131.650024,3185.949951,1772.500000,1543.800049,691.900024,643.299988,6720.350098,3101.449951,875.400024,...,3323.649902,5472.450195,2574.550049,11543.200195,1462.800049,1519.849976,432.299988,497.399994,265.670013,1272.849976
2024-08-08,7942.299805,1101.449951,3167.550049,1778.150024,1519.000000,691.549988,638.500000,6541.899902,3005.399902,875.000000,...,3333.399902,5644.100098,2529.050049,11258.000000,1459.800049,1489.550049,422.299988,487.299988,265.589996,1279.400024
2024-08-09,7972.100098,1103.800049,3187.550049,1780.849976,1533.800049,695.400024,632.000000,6587.850098,3040.600098,869.849976,...,3338.399902,6275.350098,2581.449951,11300.349609,1454.949951,1508.599976,428.850006,491.299988,267.089996,1300.900024

In [13]:
sd.head()

,ABB.NS,ADANIENSOL.NS,ADANIENT.NS,ADANIGREEN.NS,ADANIPORTS.NS,ADANIPOWER.NS,AMBUJACEM.NS,APOLLOHOSP.NS,ASIANPAINT.NS,ATGL.NS,...,TORNTPHARM.NS,TRENT.NS,TVSMOTOR.NS,ULTRACEMCO.NS,UNITDSPR.NS,VBL.NS,VEDL.NS,WIPRO.NS,ZOMATO.NS,ZYDUSLIFE.NS
Date,,,,,,,,,,,,,,,,,,,,,
1991-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08-05,7465.700195,1159.099976,3038.199951,1768.750000,1493.849976,690.849976,636.150024,6687.600098,3093.399902,857.049988,...,3167.500000,5346.899902,2493.350098,11417.250000,1400.250000,1504.750000,413.250000,485.000000,256.290009,1227.550049
2024-08-06,7465.700195,1124.849976,3072.699951,1749.599976,1494.099976,689.400024,625.549988,6657.700195,3101.750000,868.099976,...,3220.550049,5220.700195,2478.800049,11325.299805,1411.099976,1461.949951,413.899994,489.500000,249.080002,1227.699951
2024-08-07,7870.399902,1131.650024,3185.949951,1772.500000,1543.800049,691.900024,643.299988,6720.350098,3101.449951,875.400024,...,3323.649902,5472.450195,2574.550049,11543.200195,1462.800049,1519.849976,432.299988,497.399994,265.670013,1272.849976
2024-08-08,7942.299805,1101.449951,3167.550049,1778.150024,1519.000000,691.549988,638.500000,6541.899902,3005.399902,875.000000,...,3333.399902,5644.100098,2529.050049,11258.000000,1459.800049,1489.550049,422.299988,487.299988,265.589996,1279.400024
2024-08-09,7972.100098,1103.800049,3187.550049,1780.849976,1533.800049,695.400024,632.000000,6587.850098,3040.600098,869.849976,...,3338.399902,6275.350098,2581.449951,11300.349609,1454.949951,1508.599976,428.850006,491.299988,267.089996,1300.900024

In [45]:
current_date = (pd.to_datetime('today') - pd.Timedelta(days=1500)).strftime('%Y-%m-%d')  # 1460 days = 4 years
sd1 = sd[sd.index > current_date] # filter data for last 4 years
#drop columns with all NaN values
sd1.dropna(axis=1, how='any', inplace=True)
sd1_columns =sd1.columns # get column names
sd1.head()

,ABB.NS,ADANIENT.NS,ADANIGREEN.NS,ADANIPORTS.NS,ADANIPOWER.NS,AMBUJACEM.NS,APOLLOHOSP.NS,ASIANPAINT.NS,ATGL.NS,AXISBANK.NS,...,TECHM.NS,TITAN.NS,TORNTPHARM.NS,TRENT.NS,TVSMOTOR.NS,ULTRACEMCO.NS,VBL.NS,VEDL.NS,WIPRO.NS,ZYDUSLIFE.NS
Date,,,,,,,,,,,,,,,,,,,,,
2020-07-03,979.500000,160.000000,375.799988,360.399994,35.900002,195.800003,1379.800049,1695.650024,161.350006,428.450012,...,567.200012,1003.500000,1197.599976,619.500000,395.500000,3889.600098,155.133331,106.449997,224.800003,366.350006
2020-07-06,983.400024,164.199997,394.549988,359.450012,35.900002,193.899994,1410.050049,1708.849976,160.949997,434.000000,...,581.549988,1014.200012,1173.625000,630.000000,408.250000,3930.899902,155.477783,110.250000,222.649994,362.899994
2020-07-07,961.400024,168.149994,413.750000,345.950012,35.950001,193.250000,1419.250000,1745.750000,157.649994,447.350006,...,586.849976,1016.250000,1166.574951,629.950012,400.100006,3862.000000,154.255554,107.599998,224.899994,361.850006
2020-07-08,944.650024,163.000000,393.100006,340.600006,35.700001,195.550003,1393.849976,1686.250000,154.350006,444.149994,...,583.450012,991.150024,1171.400024,627.750000,384.950012,3786.649902,151.100006,110.400002,223.100006,359.700012
2020-07-09,928.500000,162.750000,373.600006,343.149994,35.549999,202.000000,1404.000000,1717.250000,154.550003,453.750000,...,577.299988,991.599976,1181.650024,621.700012,389.700012,3843.449951,153.033340,112.000000,221.600006,356.049988

In [17]:
sd1.to_csv("prices.csv")

In [18]:
def momentum_ratio(df): # function to calculate momentum ratio
    for i in df.columns:
        ret_daily = df[i].pct_change(periods=1) # percent change over daily trading days
        stdev_5 = ret_daily.rolling(window=5).std() # standard deviation over 5 trading days
        avg_ret = ret_daily.rolling(window=5).median()
        df[i+'_Year_momentum'] = avg_ret / stdev_5 
        df.dropna(inplace=True) # drop rows with NaN values
    return df

momentum_df = momentum_ratio(sd1)

In [19]:
momentum_df

,ABB.NS,ADANIENT.NS,ADANIGREEN.NS,ADANIPORTS.NS,ADANIPOWER.NS,AMBUJACEM.NS,APOLLOHOSP.NS,ASIANPAINT.NS,ATGL.NS,AXISBANK.NS,...,TECHM.NS_Year_momentum,TITAN.NS_Year_momentum,TORNTPHARM.NS_Year_momentum,TRENT.NS_Year_momentum,TVSMOTOR.NS_Year_momentum,ULTRACEMCO.NS_Year_momentum,VBL.NS_Year_momentum,VEDL.NS_Year_momentum,WIPRO.NS_Year_momentum,ZYDUSLIFE.NS_Year_momentum
Date,,,,,,,,,,,,,,,,,,,,,
2022-05-31,2427.250000,2167.550049,1888.949951,739.849976,323.250000,369.399994,3979.300049,2859.649902,2397.899902,685.200012,...,0.577363,0.126467,0.254659,0.356521,0.604598,0.816561,-0.068959,0.926308,0.774563,0.214488
2022-06-01,2456.350098,2150.899902,1848.400024,736.900024,307.100006,371.649994,3839.000000,2852.500000,2325.899902,686.049988,...,0.630917,0.130000,-0.114031,0.479740,0.734520,0.740009,0.234725,0.806248,1.082109,0.156975
2022-06-02,2418.399902,2209.399902,1925.800049,748.450012,295.350006,373.500000,3645.250000,2908.550049,2445.850098,691.549988,...,0.489461,0.130591,-0.445594,0.203679,0.169058,0.328526,0.594467,0.875479,0.420599,0.107339
2022-06-03,2315.750000,2190.000000,1855.900024,739.900024,284.100006,366.899994,3588.800049,2886.899902,2390.449951,677.299988,...,0.070339,-0.278147,-1.610446,0.205593,0.070790,-0.109025,-0.047327,0.894568,0.299737,-0.487459
2022-06-06,2363.449951,2225.050049,1802.349976,741.250000,298.299988,364.899994,3633.699951,2817.449951,2480.100098,672.200012,...,-0.033675,-0.720824,-0.713819,0.208976,-0.409697,-0.746744,-0.022180,0.638723,0.316698,-0.568005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08-05,7465.700195,3038.199951,1768.750000,1493.849976,690.849976,636.150024,6687.600098,3093.399902,857.049988,1133.500000,...,-0.326333,-0.115668,0.357919,-0.342691,0.246645,-0.348865,-0.072700,-0.257362,-0.295269,-0.283214
2024-08-06,7465.700195,3072.699951,1749.599976,1494.099976,689.400024,625.549988,6657.700195,3101.750000,868.099976,1126.099976,...,-0.287755,-0.243166,0.688573,-0.745722,-0.289517,-0.496548,-0.109650,-0.248098,-0.039876,0.008152
2024-08-07,7870.399902,3185.949951,1772.500000,1543.800049,691.900024,643.299988,6720.350098,3101.449951,875.400024,1136.800049,...,-0.327690,-0.240570,0.567501,-0.662958,-0.216139,-0.409416,-0.068351,-0.166327,-0.034767,0.006011
2024-08-08,7942.299805,3167.550049,1778.150024,1519.000000,691.549988,638.500000,6541.899902,3005.399902,875.000000,1138.150024,...,-0.326263,-0.954128,0.385778,-0.580492,-0.226052,-0.948000,-0.626806,-0.643521,-0.823601,0.261139
2024-08-09,7972.100098,3187.550049,1780.849976,1533.800049,695.400024,632.000000,6587.850098,3040.600098,869.849976,1142.750000,...,-0.202642,-0.685079,0.155061,0.529880,-0.208411,-0.399896,-0.595501,0.044210,0.376050,0.253720

In [24]:
def Calculate_Z_Score(df,columns=sd1_columns):
    for i in columns:  # calculate z score for each stock
        mean252 = df[i+'_Year_momentum'].rolling(window=252).mean() # mean over 252 trading days
        std252 = df[i+'_Year_momentum'].rolling(window=252).std() # standard deviation over 252 trading days
        df[i+'Year_Z_Score'] = (df[i]-mean252)/std252 # z score for 252 trading days
        mean126 = df[i+'_6_month_momentum'].rolling(window=126).mean() # mean over 126 trading days
        std126 = df[i+'_6_month_momentum'].rolling(window=126).std() # standard deviation over 126 trading days
        df[i+'6_month_Z_Score'] = (df[i]-mean126)/std126 # z score for 126 trading days
        df[i+'ALL_Z_Score'] = (df[i+'Year_Z_Score'] + df[i+'6_month_Z_Score'])/2 # average z score (weighted average)
    df.dropna(inplace=True) # drop rows with NaN values
    return df
momentum_df = Calculate_Z_Score(momentum_df) # calculate z score
momentum_df.head*

KeyError: 'ABB.NS_6_month_momentum'

In [21]:
momentum_df.to_csv("momentum11.csv")

In [26]:
def Calculate_Z_Score(df,columns=sd1_columns):
       for i in columns:  # calculate z score for each stock
            momentum = df[i+'_Year_momentum'].rolling(window=252).mean() # mean over 252 trading days
            mean252 = df[i+'_Year_momentum'].rolling(window=252).mean() # mean over 252 trading days
            std252 = df[i+'_Year_momentum'].rolling(window=252).std() # standard deviation over 252 trading days
            df[i+'Year_Z_Score'] = (df[i]-mean252)/std252 # z score for 252 trading days
            df.dropna(inplace=True) # drop rows with NaN values
            return df
momentum_df = Calculate_Z_Score(momentum_df) # calculate z score
momentum_df

,ABB.NS,ADANIENT.NS,ADANIGREEN.NS,ADANIPORTS.NS,ADANIPOWER.NS,AMBUJACEM.NS,APOLLOHOSP.NS,ASIANPAINT.NS,ATGL.NS,AXISBANK.NS,...,TITAN.NS_Year_momentum,TORNTPHARM.NS_Year_momentum,TRENT.NS_Year_momentum,TVSMOTOR.NS_Year_momentum,ULTRACEMCO.NS_Year_momentum,VBL.NS_Year_momentum,VEDL.NS_Year_momentum,WIPRO.NS_Year_momentum,ZYDUSLIFE.NS_Year_momentum,ABB.NSYear_Z_Score
Date,,,,,,,,,,,,,,,,,,,,,
2023-06-05,4033.000000,2433.949951,987.849976,738.799988,259.450012,439.049988,4950.200195,3199.750000,681.500000,950.849976,...,0.215111,0.039040,0.139919,-0.399326,0.199303,0.188866,-0.284224,0.487725,-0.432101,7981.545165
2023-06-06,4057.649902,2433.649902,991.849976,745.400024,263.000000,459.149994,4940.100098,3212.750000,678.400024,968.200012,...,1.276720,0.039095,0.144342,0.685746,0.073606,0.250757,-0.265816,-0.250454,0.603421,8039.022473
2023-06-07,4151.100098,2439.550049,985.549988,743.750000,274.850006,455.750000,5026.450195,3224.800049,680.049988,976.750000,...,1.488141,0.087797,0.131661,0.515521,0.317296,-0.271536,-0.132163,-0.226113,0.641448,8247.744214
2023-06-08,4112.299805,2429.149902,976.000000,736.400024,279.149994,451.700012,4926.649902,3212.250000,670.900024,962.099976,...,0.938303,0.316335,0.095447,0.578937,0.297512,-0.555261,-0.572470,-0.786015,-0.064700,8184.151261
2023-06-09,4151.200195,2451.149902,963.650024,734.950012,276.200012,455.700012,4926.700195,3180.550049,669.099976,974.750000,...,-0.032046,0.956491,0.197359,0.425749,0.453212,-0.540092,-0.863174,-0.817452,-0.425327,8255.391422
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08-05,7465.700195,3038.199951,1768.750000,1493.849976,690.849976,636.150024,6687.600098,3093.399902,857.049988,1133.500000,...,-0.115668,0.357919,-0.342691,0.246645,-0.348865,-0.072700,-0.257362,-0.295269,-0.283214,12841.476043
2024-08-06,7465.700195,3072.699951,1749.599976,1494.099976,689.400024,625.549988,6657.700195,3101.750000,868.099976,1126.099976,...,-0.243166,0.688573,-0.745722,-0.289517,-0.496548,-0.109650,-0.248098,-0.039876,0.008152,12708.958833
2024-08-07,7870.399902,3185.949951,1772.500000,1543.800049,691.900024,643.299988,6720.350098,3101.449951,875.400024,1136.800049,...,-0.240570,0.567501,-0.662958,-0.216139,-0.409416,-0.068351,-0.166327,-0.034767,0.006011,13366.495400
2024-08-08,7942.299805,3167.550049,1778.150024,1519.000000,691.549988,638.500000,6541.899902,3005.399902,875.000000,1138.150024,...,-0.954128,0.385778,-0.580492,-0.226052,-0.948000,-0.626806,-0.643521,-0.823601,0.261139,13497.842918
2024-08-09,7972.100098,3187.550049,1780.849976,1533.800049,695.400024,632.000000,6587.850098,3040.600098,869.849976,1142.750000,...,-0.685079,0.155061,0.529880,-0.208411,-0.399896,-0.595501,0.044210,0.376050,0.253720,13648.808226

In [27]:
winners = pd.DataFrame(columns=['W1','W2','W3','W4','W5','W6','W7','W8','W9','W10'])
loosers = pd.DataFrame(columns=['L1','L2','L3','L4','L5','L6','L7','L8','L9','L10'])

In [28]:
momentum_df.to_csv('momentum1.csv')
momentum_df

,ABB.NS,ADANIENT.NS,ADANIGREEN.NS,ADANIPORTS.NS,ADANIPOWER.NS,AMBUJACEM.NS,APOLLOHOSP.NS,ASIANPAINT.NS,ATGL.NS,AXISBANK.NS,...,TITAN.NS_Year_momentum,TORNTPHARM.NS_Year_momentum,TRENT.NS_Year_momentum,TVSMOTOR.NS_Year_momentum,ULTRACEMCO.NS_Year_momentum,VBL.NS_Year_momentum,VEDL.NS_Year_momentum,WIPRO.NS_Year_momentum,ZYDUSLIFE.NS_Year_momentum,ABB.NSYear_Z_Score
Date,,,,,,,,,,,,,,,,,,,,,
2023-06-05,4033.000000,2433.949951,987.849976,738.799988,259.450012,439.049988,4950.200195,3199.750000,681.500000,950.849976,...,0.215111,0.039040,0.139919,-0.399326,0.199303,0.188866,-0.284224,0.487725,-0.432101,7981.545165
2023-06-06,4057.649902,2433.649902,991.849976,745.400024,263.000000,459.149994,4940.100098,3212.750000,678.400024,968.200012,...,1.276720,0.039095,0.144342,0.685746,0.073606,0.250757,-0.265816,-0.250454,0.603421,8039.022473
2023-06-07,4151.100098,2439.550049,985.549988,743.750000,274.850006,455.750000,5026.450195,3224.800049,680.049988,976.750000,...,1.488141,0.087797,0.131661,0.515521,0.317296,-0.271536,-0.132163,-0.226113,0.641448,8247.744214
2023-06-08,4112.299805,2429.149902,976.000000,736.400024,279.149994,451.700012,4926.649902,3212.250000,670.900024,962.099976,...,0.938303,0.316335,0.095447,0.578937,0.297512,-0.555261,-0.572470,-0.786015,-0.064700,8184.151261
2023-06-09,4151.200195,2451.149902,963.650024,734.950012,276.200012,455.700012,4926.700195,3180.550049,669.099976,974.750000,...,-0.032046,0.956491,0.197359,0.425749,0.453212,-0.540092,-0.863174,-0.817452,-0.425327,8255.391422
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-08-05,7465.700195,3038.199951,1768.750000,1493.849976,690.849976,636.150024,6687.600098,3093.399902,857.049988,1133.500000,...,-0.115668,0.357919,-0.342691,0.246645,-0.348865,-0.072700,-0.257362,-0.295269,-0.283214,12841.476043
2024-08-06,7465.700195,3072.699951,1749.599976,1494.099976,689.400024,625.549988,6657.700195,3101.750000,868.099976,1126.099976,...,-0.243166,0.688573,-0.745722,-0.289517,-0.496548,-0.109650,-0.248098,-0.039876,0.008152,12708.958833
2024-08-07,7870.399902,3185.949951,1772.500000,1543.800049,691.900024,643.299988,6720.350098,3101.449951,875.400024,1136.800049,...,-0.240570,0.567501,-0.662958,-0.216139,-0.409416,-0.068351,-0.166327,-0.034767,0.006011,13366.495400
2024-08-08,7942.299805,3167.550049,1778.150024,1519.000000,691.549988,638.500000,6541.899902,3005.399902,875.000000,1138.150024,...,-0.954128,0.385778,-0.580492,-0.226052,-0.948000,-0.626806,-0.643521,-0.823601,0.261139,13497.842918
2024-08-09,7972.100098,3187.550049,1780.849976,1533.800049,695.400024,632.000000,6587.850098,3040.600098,869.849976,1142.750000,...,-0.685079,0.155061,0.529880,-0.208411,-0.399896,-0.595501,0.044210,0.376050,0.253720,13648.808226

In [38]:
# get top 10 maximum values column name in winners
# get colums containing 'Z_Score' in momentum_df
#momentum_df = momentum_df.filter(regex='Year_Z_Score')
#for i in momentum_df.index:
    #winners.loc[i] = momentum_df.loc[i].nlargest(10).index.tolist()
    #loosers.loc[i] = momentum_df.loc[i].nsmallest(10).index.tolist()

ValueError: cannot set a row with mismatched columns

In [44]:
#winners

In [39]:
#loosers

In [32]:
#winners.to_csv('winners.csv', index=False)
#loosers.to_csv('loosers.csv', index=False)