In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (20,10)

In [2]:
# download csv from url
url = 'https://archives.nseindia.com/content/indices/ind_nifty100list.csv' # Nifty 100 stocks
nifty100 = pd.read_csv(url)
nifty100= nifty100.to_csv('ind_nifty100list.csv', index=False)

symbol= pd.read_csv("ind_nifty100list.csv")  # read csv file
symbol["ticker"] = symbol["Symbol"] + ".NS"
ticker= symbol['ticker'].values.tolist() # convert to list
sd = yf.download(ticker, interval='1d')['Close'] # download data from yahoo finance

[*********************100%***********************]  100 of 100 completed

In [3]:
sd

,ABB.NS,ADANIENSOL.NS,ADANIENT.NS,ADANIGREEN.NS,ADANIPORTS.NS,ADANIPOWER.NS,AMBUJACEM.NS,APOLLOHOSP.NS,ASIANPAINT.NS,ATGL.NS,...,TRENT.NS,TVSMOTOR.NS,ULTRACEMCO.NS,UNIONBANK.NS,UNITDSPR.NS,VBL.NS,VEDL.NS,WIPRO.NS,ZOMATO.NS,ZYDUSLIFE.NS
Date,,,,,,,,,,,,,,,,,,,,,
1991-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-02,7490.750000,807.000000,2457.050049,1327.949951,1215.800049,548.900024,538.799988,7065.799805,2479.050049,772.549988,...,6805.299805,2493.399902,11648.549805,119.730003,1532.199951,632.250000,460.549988,292.274994,282.500000,974.549988
2024-12-03,7537.549805,801.849976,2514.199951,1312.800049,1288.650024,544.200012,566.549988,7126.549805,2469.399902,766.250000,...,6841.350098,2556.199951,11852.349609,126.059998,1542.949951,621.099976,468.350006,291.649994,279.850006,982.099976
2024-12-04,7664.200195,813.450012,2494.750000,1260.849976,1269.550049,537.549988,564.700012,7232.350098,2459.449951,746.650024,...,6823.799805,2518.699951,11766.799805,128.330002,1526.050049,618.900024,468.399994,294.000000,286.250000,970.349976
2024-12-05,7488.399902,822.799988,2522.550049,1229.599976,1277.050049,537.450012,571.099976,7274.750000,2452.199951,743.950012,...,6970.100098,2512.199951,11932.799805,127.800003,1530.099976,633.500000,472.500000,299.299988,299.350006,978.000000
2024-12-06,7552.399902,808.349976,2506.399902,1210.650024,1259.050049,536.099976,565.299988,7233.299805,2429.699951,731.049988,...,6999.950195,2521.550049,11848.500000,128.910004,1516.599976,644.049988,501.399994,297.350006,302.950012,995.099976

In [4]:
current_date = (pd.to_datetime('today') - pd.Timedelta(days=1500)).strftime('%Y-%m-%d')  # 1460 days = 4 years
sd1 = sd[sd.index > current_date] # filter data for last 4 years
#drop columns with all NaN values
sd1.dropna(axis=1, how='any', inplace=True)
sd1_columns =sd1.columns # get column names
sd1

,ABB.NS,ADANIENT.NS,ADANIGREEN.NS,ADANIPORTS.NS,ADANIPOWER.NS,AMBUJACEM.NS,APOLLOHOSP.NS,ASIANPAINT.NS,ATGL.NS,AXISBANK.NS,...,TITAN.NS,TORNTPHARM.NS,TRENT.NS,TVSMOTOR.NS,ULTRACEMCO.NS,UNIONBANK.NS,VBL.NS,VEDL.NS,WIPRO.NS,ZYDUSLIFE.NS
Date,,,,,,,,,,,,,,,,,,,,,
2020-11-02,875.650024,341.100006,859.200012,356.899994,35.950001,260.500000,2069.300049,2172.850098,219.350006,522.650024,...,1168.500000,1273.775024,674.700012,458.399994,4550.799805,23.950001,59.573334,94.699997,167.399994,410.649994
2020-11-03,877.400024,344.799988,830.400024,353.649994,36.049999,262.000000,2111.350098,2154.649902,222.949997,534.150024,...,1199.949951,1288.474976,654.750000,465.700012,4549.549805,23.850000,59.746666,94.849998,167.824997,437.649994
2020-11-04,878.799988,351.850006,840.900024,361.100006,36.150002,264.399994,2103.600098,2169.449951,231.350006,525.150024,...,1215.650024,1300.349976,668.500000,470.950012,4531.600098,23.799999,59.817776,92.000000,171.475006,439.299988
2020-11-05,894.150024,352.750000,854.599976,368.649994,36.400002,255.750000,2122.600098,2238.300049,235.449997,539.299988,...,1242.099976,1302.150024,679.650024,476.450012,4617.899902,24.100000,62.075554,94.250000,172.699997,442.899994
2020-11-06,937.849976,352.100006,860.000000,371.100006,37.700001,248.000000,2085.899902,2209.050049,239.850006,541.750000,...,1253.500000,1278.250000,674.200012,479.850006,4556.000000,24.500000,61.715553,94.750000,172.875000,432.299988
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-02,7490.750000,2457.050049,1327.949951,1215.800049,548.900024,538.799988,7065.799805,2479.050049,772.549988,1137.099976,...,3306.850098,3339.149902,6805.299805,2493.399902,11648.549805,119.730003,632.250000,460.549988,292.274994,974.549988
2024-12-03,7537.549805,2514.199951,1312.800049,1288.650024,544.200012,566.549988,7126.549805,2469.399902,766.250000,1160.500000,...,3332.750000,3363.100098,6841.350098,2556.199951,11852.349609,126.059998,621.099976,468.350006,291.649994,982.099976
2024-12-04,7664.200195,2494.750000,1260.849976,1269.550049,537.549988,564.700012,7232.350098,2459.449951,746.650024,1159.449951,...,3364.449951,3352.649902,6823.799805,2518.699951,11766.799805,128.330002,618.900024,468.399994,294.000000,970.349976
2024-12-05,7488.399902,2522.550049,1229.599976,1277.050049,537.450012,571.099976,7274.750000,2452.199951,743.950012,1166.400024,...,3441.050049,3361.500000,6970.100098,2512.199951,11932.799805,127.800003,633.500000,472.500000,299.299988,978.000000
2024-12-06,7552.399902,2506.399902,1210.650024,1259.050049,536.099976,565.299988,7233.299805,2429.699951,731.049988,1184.550049,...,3470.100098,3332.500000,6999.950195,2521.550049,11848.500000,128.910004,644.049988,501.399994,297.350006,995.099976

In [5]:
sd1.to_csv("prices.csv")

In [6]:
def momentum_ratio(df): # function to calculate momentum ratio
    for i in df.columns:
        ret_daily = df[i].pct_change(periods=1) # percent change over daily trading days
        stdev_5 = ret_daily.rolling(window=5).std() # standard deviation over 5 trading days
        avg_ret = ret_daily.rolling(window=5).median()
        df[i+'_Year_momentum'] = avg_ret / stdev_5 
        df.dropna(inplace=True) # drop rows with NaN values
    return df

momentum_df = momentum_ratio(sd1)

In [7]:
momentum_df

,ABB.NS,ADANIENT.NS,ADANIGREEN.NS,ADANIPORTS.NS,ADANIPOWER.NS,AMBUJACEM.NS,APOLLOHOSP.NS,ASIANPAINT.NS,ATGL.NS,AXISBANK.NS,...,TITAN.NS_Year_momentum,TORNTPHARM.NS_Year_momentum,TRENT.NS_Year_momentum,TVSMOTOR.NS_Year_momentum,ULTRACEMCO.NS_Year_momentum,UNIONBANK.NS_Year_momentum,VBL.NS_Year_momentum,VEDL.NS_Year_momentum,WIPRO.NS_Year_momentum,ZYDUSLIFE.NS_Year_momentum
Date,,,,,,,,,,,,,,,,,,,,,
2022-09-16,3180.149902,3702.199951,2316.600098,938.200012,387.750000,516.700012,4279.750000,3322.550049,3528.800049,789.299988,...,-0.100728,-0.812680,0.137382,-0.394135,-0.132835,0.574213,0.588335,0.425505,-0.177965,-0.076221
2022-09-19,3157.800049,3778.649902,2346.350098,959.599976,391.850006,564.900024,4308.200195,3316.250000,3620.050049,798.099976,...,-0.129827,-0.240559,-0.073095,-0.094282,-0.170086,0.835183,0.489832,0.399606,-0.209876,-0.340683
2022-09-20,3150.550049,3834.550049,2399.949951,970.250000,398.250000,574.349976,4559.350098,3393.199951,3674.949951,812.750000,...,-0.107810,-0.129926,-0.127546,0.085207,-0.170171,0.847032,0.330705,-0.083147,-0.192333,-0.192188
2022-09-21,3129.649902,3640.100098,2362.800049,932.900024,390.500000,541.349976,4604.799805,3356.050049,3565.500000,806.549988,...,-0.377590,-0.127151,0.328625,0.080514,-0.635477,0.535544,0.339251,-0.206764,-0.196889,-0.563017
2022-09-22,3144.100098,3716.300049,2363.600098,946.650024,396.250000,534.049988,4608.899902,3436.000000,3629.899902,789.200012,...,0.161099,0.063186,1.012661,-0.066610,-0.599167,-0.285617,0.284950,-0.238277,-0.463927,-0.408409
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-02,7490.750000,2457.050049,1327.949951,1215.800049,548.900024,538.799988,7065.799805,2479.050049,772.549988,1137.099976,...,0.324485,-0.017314,0.083561,0.430844,0.062995,-0.044617,0.975328,1.193964,0.698460,-0.185947
2024-12-03,7537.549805,2514.199951,1312.800049,1288.650024,544.200012,566.549988,7126.549805,2469.399902,766.250000,1160.500000,...,0.451430,0.260986,0.358918,0.536694,0.884960,-0.021106,-0.099783,1.403334,-0.166082,0.900114
2024-12-04,7664.200195,2494.750000,1260.849976,1269.550049,537.549988,564.700012,7232.350098,2459.449951,746.650024,1159.449951,...,0.579277,0.255140,0.163766,0.421041,0.818412,-0.020836,-0.172892,1.790520,0.646120,0.670151
2024-12-05,7488.399902,2522.550049,1229.599976,1277.050049,537.450012,571.099976,7274.750000,2452.199951,743.950012,1166.400024,...,1.825976,0.278909,0.580029,0.457164,1.046147,-0.021491,-0.188119,1.197870,1.350263,0.715196
2024-12-06,7552.399902,2506.399902,1210.650024,1259.050049,536.099976,565.299988,7233.299805,2429.699951,731.049988,1184.550049,...,1.426756,0.415570,0.467387,0.214965,0.718653,0.332098,0.960625,0.656242,0.802897,0.727585

In [8]:
def Calculate_Z_Score(df,columns=sd1_columns):
    for i in columns:  # calculate z score for each stock
        mean252 = df[i+'_Year_momentum'].rolling(window=252).mean() # mean over 252 trading days
        std252 = df[i+'_Year_momentum'].rolling(window=252).std() # standard deviation over 252 trading days
        df[i+'Year_Z_Score'] = (df[i]-mean252)/std252 # z score for 252 trading days
        mean126 = df[i+'_6_month_momentum'].rolling(window=126).mean() # mean over 126 trading days
        std126 = df[i+'_6_month_momentum'].rolling(window=126).std() # standard deviation over 126 trading days
        df[i+'6_month_Z_Score'] = (df[i]-mean126)/std126 # z score for 126 trading days
        df[i+'ALL_Z_Score'] = (df[i+'Year_Z_Score'] + df[i+'6_month_Z_Score'])/2 # average z score (weighted average)
    df.dropna(inplace=True) # drop rows with NaN values
    return df
momentum_df = Calculate_Z_Score(momentum_df) # calculate z score
momentum_df

KeyError: 'ABB.NS_6_month_momentum'

In [9]:
momentum_df.to_csv("momentum11.csv")

In [10]:
def Calculate_Z_Score(df,columns=sd1_columns):
       for i in columns:  # calculate z score for each stock
            momentum = df[i+'_Year_momentum'].rolling(window=252).mean() # mean over 252 trading days
            mean252 = df[i+'_Year_momentum'].rolling(window=252).mean() # mean over 252 trading days
            std252 = df[i+'_Year_momentum'].rolling(window=252).std() # standard deviation over 252 trading days
            df[i+'Year_Z_Score'] = (df[i]-mean252)/std252 # z score for 252 trading days
            df.dropna(inplace=True) # drop rows with NaN values
            return df
momentum_df = Calculate_Z_Score(momentum_df) # calculate z score
momentum_df

,ABB.NS,ADANIENT.NS,ADANIGREEN.NS,ADANIPORTS.NS,ADANIPOWER.NS,AMBUJACEM.NS,APOLLOHOSP.NS,ASIANPAINT.NS,ATGL.NS,AXISBANK.NS,...,TORNTPHARM.NS_Year_momentum,TRENT.NS_Year_momentum,TVSMOTOR.NS_Year_momentum,ULTRACEMCO.NS_Year_momentum,UNIONBANK.NS_Year_momentum,VBL.NS_Year_momentum,VEDL.NS_Year_momentum,WIPRO.NS_Year_momentum,ZYDUSLIFE.NS_Year_momentum,ABB.NSYear_Z_Score
Date,,,,,,,,,,,,,,,,,,,,,
2023-09-21,4276.200195,2479.250000,1023.450012,831.099976,382.450012,426.100006,5020.049805,3244.199951,639.599976,1014.450012,...,-0.012832,-0.321686,0.424675,-0.950079,0.587615,0.168977,0.028156,-0.271116,-0.371328,9095.414491
2023-09-22,4187.000000,2464.899902,1018.799988,827.049988,383.899994,420.950012,4989.549805,3274.850098,636.650024,1018.250000,...,-0.013751,0.586057,-0.200120,-1.572824,0.521807,0.186344,-0.571844,-0.858947,-0.841966,8770.572446
2023-09-25,4176.899902,2482.100098,1013.799988,825.650024,381.149994,422.899994,5097.049805,3323.250000,634.299988,1018.950012,...,-0.246557,0.148791,-0.262551,-1.753652,0.214677,0.506256,-0.600888,-1.435755,-0.773931,8608.955038
2023-09-26,4205.200195,2457.949951,1012.299988,821.349976,377.500000,429.750000,5053.700195,3292.800049,634.099976,1014.150024,...,-1.026614,0.154496,-0.293450,-1.380621,0.056741,0.426894,-0.647888,-1.173222,-0.800063,8683.807444
2023-09-27,4233.350098,2483.300049,1018.750000,830.700012,375.350006,430.450012,5105.350098,3301.800049,627.650024,1025.199951,...,-0.654542,-0.071434,-0.185193,0.217559,0.053892,0.468188,-0.232880,-0.250425,-0.458598,8758.850393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-02,7490.750000,2457.050049,1327.949951,1215.800049,548.900024,538.799988,7065.799805,2479.050049,772.549988,1137.099976,...,-0.017314,0.083561,0.430844,0.062995,-0.044617,0.975328,1.193964,0.698460,-0.185947,12457.332156
2024-12-03,7537.549805,2514.199951,1312.800049,1288.650024,544.200012,566.549988,7126.549805,2469.399902,766.250000,1160.500000,...,0.260986,0.358918,0.536694,0.884960,-0.021106,-0.099783,1.403334,-0.166082,0.900114,12527.863742
2024-12-04,7664.200195,2494.750000,1260.849976,1269.550049,537.549988,564.700012,7232.350098,2459.449951,746.650024,1159.449951,...,0.255140,0.163766,0.421041,0.818412,-0.020836,-0.172892,1.790520,0.646120,0.670151,12729.951629
2024-12-05,7488.399902,2522.550049,1229.599976,1277.050049,537.450012,571.099976,7274.750000,2452.199951,743.950012,1166.400024,...,0.278909,0.580029,0.457164,1.046147,-0.021491,-0.188119,1.197870,1.350263,0.715196,12432.938941
2024-12-06,7552.399902,2506.399902,1210.650024,1259.050049,536.099976,565.299988,7233.299805,2429.699951,731.049988,1184.550049,...,0.415570,0.467387,0.214965,0.718653,0.332098,0.960625,0.656242,0.802897,0.727585,12528.286106

In [11]:
winners = pd.DataFrame(columns=['W1','W2','W3','W4','W5','W6','W7','W8','W9','W10'])
loosers = pd.DataFrame(columns=['L1','L2','L3','L4','L5','L6','L7','L8','L9','L10'])

In [12]:
m1=momentum_df.to_csv('momentum1.csv')
momentum_df

,ABB.NS,ADANIENT.NS,ADANIGREEN.NS,ADANIPORTS.NS,ADANIPOWER.NS,AMBUJACEM.NS,APOLLOHOSP.NS,ASIANPAINT.NS,ATGL.NS,AXISBANK.NS,...,TORNTPHARM.NS_Year_momentum,TRENT.NS_Year_momentum,TVSMOTOR.NS_Year_momentum,ULTRACEMCO.NS_Year_momentum,UNIONBANK.NS_Year_momentum,VBL.NS_Year_momentum,VEDL.NS_Year_momentum,WIPRO.NS_Year_momentum,ZYDUSLIFE.NS_Year_momentum,ABB.NSYear_Z_Score
Date,,,,,,,,,,,,,,,,,,,,,
2023-09-21,4276.200195,2479.250000,1023.450012,831.099976,382.450012,426.100006,5020.049805,3244.199951,639.599976,1014.450012,...,-0.012832,-0.321686,0.424675,-0.950079,0.587615,0.168977,0.028156,-0.271116,-0.371328,9095.414491
2023-09-22,4187.000000,2464.899902,1018.799988,827.049988,383.899994,420.950012,4989.549805,3274.850098,636.650024,1018.250000,...,-0.013751,0.586057,-0.200120,-1.572824,0.521807,0.186344,-0.571844,-0.858947,-0.841966,8770.572446
2023-09-25,4176.899902,2482.100098,1013.799988,825.650024,381.149994,422.899994,5097.049805,3323.250000,634.299988,1018.950012,...,-0.246557,0.148791,-0.262551,-1.753652,0.214677,0.506256,-0.600888,-1.435755,-0.773931,8608.955038
2023-09-26,4205.200195,2457.949951,1012.299988,821.349976,377.500000,429.750000,5053.700195,3292.800049,634.099976,1014.150024,...,-1.026614,0.154496,-0.293450,-1.380621,0.056741,0.426894,-0.647888,-1.173222,-0.800063,8683.807444
2023-09-27,4233.350098,2483.300049,1018.750000,830.700012,375.350006,430.450012,5105.350098,3301.800049,627.650024,1025.199951,...,-0.654542,-0.071434,-0.185193,0.217559,0.053892,0.468188,-0.232880,-0.250425,-0.458598,8758.850393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-02,7490.750000,2457.050049,1327.949951,1215.800049,548.900024,538.799988,7065.799805,2479.050049,772.549988,1137.099976,...,-0.017314,0.083561,0.430844,0.062995,-0.044617,0.975328,1.193964,0.698460,-0.185947,12457.332156
2024-12-03,7537.549805,2514.199951,1312.800049,1288.650024,544.200012,566.549988,7126.549805,2469.399902,766.250000,1160.500000,...,0.260986,0.358918,0.536694,0.884960,-0.021106,-0.099783,1.403334,-0.166082,0.900114,12527.863742
2024-12-04,7664.200195,2494.750000,1260.849976,1269.550049,537.549988,564.700012,7232.350098,2459.449951,746.650024,1159.449951,...,0.255140,0.163766,0.421041,0.818412,-0.020836,-0.172892,1.790520,0.646120,0.670151,12729.951629
2024-12-05,7488.399902,2522.550049,1229.599976,1277.050049,537.450012,571.099976,7274.750000,2452.199951,743.950012,1166.400024,...,0.278909,0.580029,0.457164,1.046147,-0.021491,-0.188119,1.197870,1.350263,0.715196,12432.938941
2024-12-06,7552.399902,2506.399902,1210.650024,1259.050049,536.099976,565.299988,7233.299805,2429.699951,731.049988,1184.550049,...,0.415570,0.467387,0.214965,0.718653,0.332098,0.960625,0.656242,0.802897,0.727585,12528.286106

In [13]:
#get top 10 maximum values column name in winners
#get colums containing 'Year_momentum' in momentum_df
#momentum_df = momentum_df.filter(regex='NS_Year_momentum')
momentum_df
for i in momentum_df.index:
    winners.loc[i] = momentum_df.loc[i].nlargest(10).index.tolist()
    loosers.loc[i] = momentum_df.loc[i].nsmallest(10).index.tolist()

In [14]:
winners

,W1,W2,W3,W4,W5,W6,W7,W8,W9,W10
2023-09-21,SHREECEM.NS,BOSCHLTD.NS,MARUTI.NS,ABB.NSYear_Z_Score,ULTRACEMCO.NS,BAJFINANCE.NS,BAJAJHLDNG.NS,LTIM.NS,BAJAJ-AUTO.NS,APOLLOHOSP.NS
2023-09-22,SHREECEM.NS,BOSCHLTD.NS,MARUTI.NS,ABB.NSYear_Z_Score,ULTRACEMCO.NS,BAJFINANCE.NS,BAJAJHLDNG.NS,LTIM.NS,BAJAJ-AUTO.NS,APOLLOHOSP.NS
2023-09-25,SHREECEM.NS,BOSCHLTD.NS,MARUTI.NS,ABB.NSYear_Z_Score,ULTRACEMCO.NS,BAJFINANCE.NS,BAJAJHLDNG.NS,LTIM.NS,APOLLOHOSP.NS,BAJAJ-AUTO.NS
2023-09-26,SHREECEM.NS,BOSCHLTD.NS,MARUTI.NS,ABB.NSYear_Z_Score,ULTRACEMCO.NS,BAJFINANCE.NS,BAJAJHLDNG.NS,LTIM.NS,BAJAJ-AUTO.NS,APOLLOHOSP.NS
2023-09-27,SHREECEM.NS,BOSCHLTD.NS,MARUTI.NS,ABB.NSYear_Z_Score,ULTRACEMCO.NS,BAJFINANCE.NS,BAJAJHLDNG.NS,LTIM.NS,APOLLOHOSP.NS,BAJAJ-AUTO.NS
...,...,...,...,...,...,...,...,...,...,...
2024-12-02,BOSCHLTD.NS,SHREECEM.NS,ABB.NSYear_Z_Score,ULTRACEMCO.NS,MARUTI.NS,BAJAJHLDNG.NS,BAJAJ-AUTO.NS,NAUKRI.NS,SIEMENS.NS,ABB.NS
2024-12-03,BOSCHLTD.NS,SHREECEM.NS,ABB.NSYear_Z_Score,ULTRACEMCO.NS,MARUTI.NS,BAJAJHLDNG.NS,BAJAJ-AUTO.NS,NAUKRI.NS,SIEMENS.NS,ABB.NS
2024-12-04,BOSCHLTD.NS,SHREECEM.NS,ABB.NSYear_Z_Score,ULTRACEMCO.NS,MARUTI.NS,BAJAJHLDNG.NS,BAJAJ-AUTO.NS,NAUKRI.NS,SIEMENS.NS,ABB.NS
2024-12-05,BOSCHLTD.NS,SHREECEM.NS,ABB.NSYear_Z_Score,ULTRACEMCO.NS,MARUTI.NS,BAJAJHLDNG.NS,BAJAJ-AUTO.NS,NAUKRI.NS,SIEMENS.NS,ABB.NS
2024-12-06,BOSCHLTD.NS,SHREECEM.NS,ABB.NSYear_Z_Score,ULTRACEMCO.NS,MARUTI.NS,BAJAJHLDNG.NS,BAJAJ-AUTO.NS,NAUKRI.NS,SIEMENS.NS,ABB.NS

In [15]:
loosers

,L1,L2,L3,L4,L5,L6,L7,L8,L9,L10
2023-09-21,SIEMENS.NS_Year_momentum,LTIM.NS_Year_momentum,ULTRACEMCO.NS_Year_momentum,IRCTC.NS_Year_momentum,DLF.NS_Year_momentum,GODREJCP.NS_Year_momentum,RELIANCE.NS_Year_momentum,KOTAKBANK.NS_Year_momentum,TATACONSUM.NS_Year_momentum,BHEL.NS_Year_momentum
2023-09-22,IRCTC.NS_Year_momentum,DLF.NS_Year_momentum,SIEMENS.NS_Year_momentum,DIVISLAB.NS_Year_momentum,ULTRACEMCO.NS_Year_momentum,AMBUJACEM.NS_Year_momentum,ABB.NS_Year_momentum,TATASTEEL.NS_Year_momentum,GODREJCP.NS_Year_momentum,JINDALSTEL.NS_Year_momentum
2023-09-25,ULTRACEMCO.NS_Year_momentum,HCLTECH.NS_Year_momentum,WIPRO.NS_Year_momentum,SIEMENS.NS_Year_momentum,ABB.NS_Year_momentum,SBILIFE.NS_Year_momentum,AMBUJACEM.NS_Year_momentum,SHREECEM.NS_Year_momentum,DRREDDY.NS_Year_momentum,DIVISLAB.NS_Year_momentum
2023-09-26,HCLTECH.NS_Year_momentum,SBILIFE.NS_Year_momentum,ULTRACEMCO.NS_Year_momentum,CIPLA.NS_Year_momentum,DMART.NS_Year_momentum,ICICIGI.NS_Year_momentum,TITAN.NS_Year_momentum,WIPRO.NS_Year_momentum,TORNTPHARM.NS_Year_momentum,ATGL.NS_Year_momentum
2023-09-27,ICICIGI.NS_Year_momentum,DMART.NS_Year_momentum,HAL.NS_Year_momentum,TITAN.NS_Year_momentum,HDFCBANK.NS_Year_momentum,CIPLA.NS_Year_momentum,SBILIFE.NS_Year_momentum,HCLTECH.NS_Year_momentum,ATGL.NS_Year_momentum,TORNTPHARM.NS_Year_momentum
...,...,...,...,...,...,...,...,...,...,...
2024-12-02,POWERGRID.NS_Year_momentum,NTPC.NS_Year_momentum,INDUSINDBK.NS_Year_momentum,JSWENERGY.NS_Year_momentum,KOTAKBANK.NS_Year_momentum,SBIN.NS_Year_momentum,LT.NS_Year_momentum,HEROMOTOCO.NS_Year_momentum,BRITANNIA.NS_Year_momentum,BAJAJHLDNG.NS_Year_momentum
2024-12-03,BRITANNIA.NS_Year_momentum,ICICIPRULI.NS_Year_momentum,JSWENERGY.NS_Year_momentum,INDUSINDBK.NS_Year_momentum,HDFCLIFE.NS_Year_momentum,DABUR.NS_Year_momentum,POWERGRID.NS_Year_momentum,HEROMOTOCO.NS_Year_momentum,ASIANPAINT.NS_Year_momentum,GODREJCP.NS_Year_momentum
2024-12-04,HEROMOTOCO.NS_Year_momentum,POWERGRID.NS_Year_momentum,JSWENERGY.NS_Year_momentum,BRITANNIA.NS_Year_momentum,GODREJCP.NS_Year_momentum,DABUR.NS_Year_momentum,ICICIPRULI.NS_Year_momentum,HINDUNILVR.NS_Year_momentum,ITC.NS_Year_momentum,ASIANPAINT.NS_Year_momentum
2024-12-05,ADANIPOWER.NS_Year_momentum,ICICIPRULI.NS_Year_momentum,HEROMOTOCO.NS_Year_momentum,BHEL.NS_Year_momentum,ASIANPAINT.NS_Year_momentum,HDFCLIFE.NS_Year_momentum,POWERGRID.NS_Year_momentum,ATGL.NS_Year_momentum,JSWENERGY.NS_Year_momentum,ICICIGI.NS_Year_momentum
2024-12-06,ICICIPRULI.NS_Year_momentum,ADANIPOWER.NS_Year_momentum,ASIANPAINT.NS_Year_momentum,ADANIGREEN.NS_Year_momentum,ATGL.NS_Year_momentum,CIPLA.NS_Year_momentum,BHARTIARTL.NS_Year_momentum,HDFCLIFE.NS_Year_momentum,HINDUNILVR.NS_Year_momentum,HEROMOTOCO.NS_Year_momentum

In [32]:
winners.to_csv('winners.csv', index=False)
loosers.to_csv('loosers.csv', index=False)