In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (20,10)

In [ ]:
# download csv from url
#url = 'https://archives.nseindia.com/content/indices/ind_nifty100list.csv' # Nifty 100 stocks
#nifty100 = pd.read_csv(url)
nifty100.to_csv('ind_nifty50list.csv', index=False)
symbol= pd.read_csv("ind_nifty100list.csv")  # read csv file
symbol["ticker"] = symbol["Symbol"] + ".NS"
ticker= symbol['ticker'].values.tolist() # convert to list
sd = yf.download(ticker, interval='1d')['Close'] # download data from yahoo finance
sd

[***                    7%                       ]  7 of 101 completed

Exception in thread Thread-216:
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\anaconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\base.py", line 279, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'

[*****                 10%                       ]  10 of 101 completed

Exception in thread Thread-219:
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\anaconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\base.py", line 279, in history
Exception in thread Thread-222:
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'
    self.run()
  File "C:\Users\admin\anaconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\base.py", line 279, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'

[********              16%                       ]  16 of 101 completed

Exception in thread Thread-228:
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\anaconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\base.py", line 279, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'

[*********             18%                       ]  18 of 101 completed

Exception in thread Thread-230:
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\anaconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\base.py", line 279, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'
Exception in thread Thread-232:
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\anaconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\base.py", line 279, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'

[**********            20%                       ]  20 of 101 completed

Exception in thread Thread-236:
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\anaconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\base.py", line 279, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'

[***********           22%                       ]  22 of 101 completed

Exception in thread Thread-237:
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\anaconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\base.py", line 279, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'

[************          25%                       ]  25 of 101 completed

Exception in thread Thread-241:
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\anaconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\base.py", line 279, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'
Exception in thread Thread-242:
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\anaconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\base.py", line 279, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'
Exception in thread Thread-244:
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\anaconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\base.py", line 279, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'

[***************       32%                       ]  32 of 101 completed

Exception in thread Thread-252:
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\anaconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\base.py", line 279, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'

[****************      33%                       ]  33 of 101 completed

Exception in thread Thread-253:
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\anaconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\base.py", line 279, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'
Exception in thread Thread-254:
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\anaconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\base.py", line 279, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'

[******************    38%                       ]  38 of 101 completed

Exception in thread Thread-260:
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\anaconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\base.py", line 279, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'
Exception in thread Thread-262:
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\anaconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\base.py", line 279, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'

[*******************   39%                       ]  39 of 101 completed

Exception in thread Thread-263:
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\anaconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\base.py", line 279, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'
Exception in thread Thread-266:
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\anaconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\base.py", line 279, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'

[**********************50%                       ]  50 of 101 completed

Exception in thread Thread-279:
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\anaconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\base.py", line 279, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'
Exception in thread Thread-276:
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\anaconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\base.py", line 279, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'

[**********************50%                       ]  51 of 101 completed

Exception in thread Thread-278:
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\anaconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\base.py", line 279, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'
Exception in thread Thread-280:
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\anaconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\base.py", line 279, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'

[**********************51%                       ]  52 of 101 completed

Exception in thread Thread-283:
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\anaconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\base.py", line 279, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'

[**********************60%****                   ]  61 of 101 completed

Exception in thread Thread-294:
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\anaconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\base.py", line 279, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'

[**********************63%*****                  ]  64 of 101 completed

Exception in thread Thread-296:
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\anaconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\base.py", line 279, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'

[**********************67%*******                ]  68 of 101 completed

Exception in thread Thread-301:
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\anaconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\multitasking\__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 188, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\multi.py", line 202, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\Users\admin\anaconda3\lib\site-packages\yfinance\base.py", line 279, in history
    df.index = df.index.tz_localize("UTC").tz_convert(
AttributeError: 'Index' object has no attribute 'tz_localize'

[**********************73%**********             ]  74 of 101 completed

In [5]:
symbol

,Company Name,Industry,Symbol,Series,ISIN Code,ticker
0,ABB India Ltd.,Capital Goods,ABB,EQ,INE117A01022,ABB.NS
1,Adani Energy Solutions Ltd.,Power,ADANIENSOL,EQ,INE931S01010,ADANIENSOL.NS
2,Adani Enterprises Ltd.,Metals & Mining,ADANIENT,EQ,INE423A01024,ADANIENT.NS
3,Adani Green Energy Ltd.,Power,ADANIGREEN,EQ,INE364U01010,ADANIGREEN.NS
4,Adani Ports and Special Economic Zone Ltd.,Services,ADANIPORTS,EQ,INE742F01042,ADANIPORTS.NS
...,...,...,...,...,...,...
96,Varun Beverages Ltd.,Fast Moving Consumer Goods,VBL,EQ,INE200M01021,VBL.NS
97,Vedanta Ltd.,Metals & Mining,VEDL,EQ,INE205A01025,VEDL.NS
98,Wipro Ltd.,Information Technology,WIPRO,EQ,INE075A01022,WIPRO.NS
99,Zomato Ltd.,Consumer Services,ZOMATO,EQ,INE758T01015,ZOMATO.NS
100,Zydus Lifesciences Ltd.,Healthcare,ZYDUSLIFE,EQ,INE010B01027,ZYDUSLIFE.NS

In [3]:
current_date = (pd.to_datetime('today') - pd.Timedelta(days=1500)).strftime('%Y-%m-%d')  # 1460 days = 4 years
sd1 = sd[sd.index > current_date] # filter data for last 4 years
# drop columns with all NaN values
sd1.dropna(axis=1, how='any', inplace=True)
sd1_columns =sd1.columns # get column names
sd1

,ABB.NS,ACC.NS,ADANIENT.NS,ADANIGREEN.NS,ADANIPORTS.NS,ADANITRANS.NS,AMBUJACEM.NS,APOLLOHOSP.NS,ASIANPAINT.NS,ATGL.NS,...,TATAPOWER.NS,TATASTEEL.NS,TCS.NS,TECHM.NS,TITAN.NS,ULTRACEMCO.NS,UPL.NS,VBL.NS,VEDL.NS,WIPRO.NS
Date,,,,,,,,,,,,,,,,,,,,,
2019-05-30,1574.300049,1708.150024,158.100006,44.599998,409.299988,233.750000,233.000000,1203.000000,1374.599976,171.149994,...,70.500000,48.794998,2146.300049,735.000000,1240.599976,4758.899902,670.566650,136.422226,164.000000,288.000000
2019-05-31,1569.300049,1686.000000,154.750000,43.299999,416.399994,235.899994,230.600006,1238.800049,1407.300049,164.850006,...,68.800003,48.830002,2196.550049,760.349976,1235.750000,4760.100098,665.966675,138.222229,160.550003,286.399994
2019-06-03,1593.349976,1725.199951,159.050003,44.099998,424.750000,235.699997,237.149994,1357.300049,1459.250000,178.649994,...,68.349998,49.764999,2242.300049,757.599976,1266.250000,4762.299805,671.400024,140.029633,164.199997,291.299988
2019-06-04,1561.650024,1657.650024,157.600006,45.200001,425.549988,231.800003,226.949997,1332.300049,1421.500000,181.699997,...,66.699997,49.764999,2183.100098,748.299988,1248.000000,4692.000000,673.966675,139.622223,165.899994,293.750000
2019-06-06,1529.800049,1592.150024,153.149994,44.349998,426.299988,228.050003,221.750000,1342.150024,1428.550049,170.350006,...,65.099998,48.459999,2166.100098,738.000000,1269.449951,4571.200195,674.799988,138.970367,163.100006,291.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-07-03,4411.250000,1825.099976,2385.500000,942.849976,737.400024,773.250000,435.850006,5068.500000,3358.699951,657.700012,...,221.899994,113.099998,3272.300049,1121.449951,3038.300049,8463.799805,680.299988,818.349976,278.100006,391.600006
2023-07-04,4360.700195,1820.449951,2387.699951,946.000000,741.700012,770.599976,432.700012,5109.950195,3347.699951,650.150024,...,220.649994,112.400002,3308.850098,1148.000000,3074.649902,8411.700195,676.950012,804.049988,277.549988,395.950012
2023-07-05,4390.600098,1820.800049,2399.149902,948.200012,742.750000,770.000000,432.399994,5077.649902,3374.399902,649.900024,...,221.699997,112.949997,3319.949951,1175.000000,3099.850098,8377.200195,669.799988,825.650024,277.450012,393.899994
2023-07-06,4400.149902,1820.349976,2402.899902,962.200012,740.049988,769.349976,431.500000,5283.049805,3399.399902,648.750000,...,229.600006,112.650002,3322.899902,1179.250000,3106.399902,8410.200195,672.750000,813.849976,280.000000,396.200012
2023-07-07,4399.750000,1791.500000,2379.600098,951.000000,718.700012,759.849976,417.899994,5146.250000,3343.699951,643.250000,...,228.000000,111.599998,3329.250000,1156.000000,3144.000000,8336.450195,663.000000,821.150024,280.549988,395.850006

In [16]:
sd1.to_csv("prices.csv")

In [4]:
def momentum_ratio(df): # function to calculate momentum ratio
    for i in df.columns:
        returns252 = df[i].pct_change(periods=252) # percent change over 252 trading days
        stds252 = returns252.rolling(window=252).std() # standard deviation over 252 trading days
        returns126 = df[i].pct_change(periods=126) # percent change over 126 trading days
        stds126 = returns126.rolling(window=126).std() # standard deviation over 126 trading days
        df[i+'_Year_momentum'] = returns252/stds252 # momentum ratio for 252 trading days
        df[i+'_6_month_momentum'] = returns126/stds126 # momentum ratio for 126 trading days
    df.dropna(inplace=True) # drop rows with NaN values
    return df

momentum_df = momentum_ratio(sd1)

In [5]:
momentum_df

,ABB.NS,ACC.NS,ADANIENT.NS,ADANIGREEN.NS,ADANIPORTS.NS,ADANITRANS.NS,AMBUJACEM.NS,APOLLOHOSP.NS,ASIANPAINT.NS,ATGL.NS,...,ULTRACEMCO.NS_Year_momentum,ULTRACEMCO.NS_6_month_momentum,UPL.NS_Year_momentum,UPL.NS_6_month_momentum,VBL.NS_Year_momentum,VBL.NS_6_month_momentum,VEDL.NS_Year_momentum,VEDL.NS_6_month_momentum,WIPRO.NS_Year_momentum,WIPRO.NS_6_month_momentum
Date,,,,,,,,,,,,,,,,,,,,,
2021-06-11,1648.550049,2024.500000,1601.599976,1217.699951,839.750000,1602.599976,337.700012,3336.550049,2956.250000,1626.199951,...,1.930949,2.257411,2.004224,2.649296,3.903031,4.594442,1.627671,2.264231,2.599585,3.663342
2021-06-14,1660.599976,2040.550049,1501.449951,1212.900024,768.450012,1522.500000,340.350006,3350.199951,2949.899902,1544.900024,...,2.048027,1.975817,2.064851,2.662958,3.721364,3.826821,1.733063,2.103969,2.735650,3.669562
2021-06-15,1693.949951,2042.949951,1538.849976,1212.199951,761.849976,1446.400024,341.450012,3298.300049,3042.199951,1467.699951,...,1.940739,2.082281,2.147276,2.449924,3.715459,3.811787,1.642080,1.855894,2.807622,3.749428
2021-06-16,1720.300049,2020.500000,1448.300049,1182.750000,706.700012,1374.099976,338.899994,3294.199951,3018.699951,1394.349976,...,1.939686,2.299249,2.185718,3.107132,3.365064,3.635035,1.598538,1.751836,2.662180,3.818286
2021-06-17,1716.500000,2042.199951,1367.699951,1123.650024,646.900024,1305.400024,346.250000,3240.600098,3060.300049,1324.650024,...,1.978260,2.370986,2.066054,3.094326,3.440475,3.708693,1.530873,1.650530,2.716251,3.969093
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-07-03,4411.250000,1825.099976,2385.500000,942.849976,737.400024,773.250000,435.850006,5068.500000,3358.699951,657.700012,...,2.819219,3.164366,0.818641,-0.640519,5.194161,1.854651,2.241118,-0.546276,-0.674299,0.368655
2023-07-04,4360.700195,1820.449951,2387.699951,946.000000,741.700012,770.599976,432.700012,5109.950195,3347.699951,650.150024,...,2.611510,3.236188,0.403345,-0.826191,5.006265,1.705319,1.880060,-0.513160,-0.700230,0.595784
2023-07-05,4390.600098,1820.800049,2399.149902,948.200012,742.750000,770.000000,432.399994,5077.649902,3374.399902,649.900024,...,2.538193,3.390812,0.282270,-0.943820,5.267283,1.788540,1.543440,-0.554513,-0.794643,0.228331
2023-07-06,4400.149902,1820.349976,2402.899902,962.200012,740.049988,769.349976,431.500000,5283.049805,3399.399902,648.750000,...,2.484058,3.557853,0.594088,-0.791897,5.092900,1.968579,1.729680,-0.532049,-0.586790,0.247539
2023-07-07,4399.750000,1791.500000,2379.600098,951.000000,718.700012,759.849976,417.899994,5146.250000,3343.699951,643.250000,...,2.413145,3.240566,0.658100,-1.085261,5.142577,2.053537,2.118486,-0.658308,-0.481926,0.199576

In [6]:
def Calculate_Z_Score(df,columns=sd1_columns):
    for i in columns:  # calculate z score for each stock
        mean252 = df[i+'_Year_momentum'].rolling(window=252).mean() # mean over 252 trading days
        std252 = df[i+'_Year_momentum'].rolling(window=252).std() # standard deviation over 252 trading days
        df[i+'Year_Z_Score'] = (df[i]-mean252)/std252 # z score for 252 trading days
        mean126 = df[i+'_6_month_momentum'].rolling(window=126).mean() # mean over 126 trading days
        std126 = df[i+'_6_month_momentum'].rolling(window=126).std() # standard deviation over 126 trading days
        df[i+'6_month_Z_Score'] = (df[i]-mean126)/std126 # z score for 126 trading days
        df[i+'ALL_Z_Score'] = (df[i+'Year_Z_Score'] + df[i+'6_month_Z_Score'])/2 # average z score (weighted average)
    df.dropna(inplace=True) # drop rows with NaN values
    return df
momentum_df = Calculate_Z_Score(momentum_df) # calculate z score
momentum_df

,ABB.NS,ACC.NS,ADANIENT.NS,ADANIGREEN.NS,ADANIPORTS.NS,ADANITRANS.NS,AMBUJACEM.NS,APOLLOHOSP.NS,ASIANPAINT.NS,ATGL.NS,...,UPL.NSALL_Z_Score,VBL.NSYear_Z_Score,VBL.NS6_month_Z_Score,VBL.NSALL_Z_Score,VEDL.NSYear_Z_Score,VEDL.NS6_month_Z_Score,VEDL.NSALL_Z_Score,WIPRO.NSYear_Z_Score,WIPRO.NS6_month_Z_Score,WIPRO.NSALL_Z_Score
Date,,,,,,,,,,,,,,,,,,,,,
2022-06-15,2304.699951,2122.649902,2184.600098,1757.849976,703.750000,2057.300049,361.950012,3722.699951,2661.149902,2351.800049,...,1194.062297,579.371413,435.793977,507.582695,467.645976,195.480280,331.563128,445.242626,372.423293,408.832959
2022-06-16,2243.949951,2084.250000,2083.000000,1711.099976,681.700012,2124.649902,359.399994,3663.649902,2657.449951,2376.500000,...,1127.416135,577.985460,424.865510,501.425485,423.739725,176.478869,300.109297,424.388329,357.175177,390.781753
2022-06-17,2173.149902,2055.100098,2095.800049,1711.250000,668.950012,2032.599976,357.350006,3701.250000,2580.199951,2149.050049,...,1076.206837,559.993211,406.309047,483.151129,413.159636,171.595477,292.377557,404.561425,341.750128,373.155776
2022-06-20,2187.949951,2060.399902,2079.850098,1743.650024,663.150024,2060.250000,357.299988,3811.699951,2660.699951,1989.199951,...,1011.720441,563.713885,401.143463,482.428674,355.172217,146.785094,250.978656,411.802297,349.365699,380.583998
2022-06-21,2227.850098,2086.250000,2161.800049,1809.099976,689.099976,2215.050049,358.899994,3808.199951,2678.350098,2382.899902,...,1019.045577,554.247584,389.359516,471.803550,359.134607,148.215013,253.674810,419.953100,359.079799,389.516450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-07-03,4411.250000,1825.099976,2385.500000,942.849976,737.400024,773.250000,435.850006,5068.500000,3358.699951,657.700012,...,935.610965,1059.700321,813.981121,936.840721,443.633363,348.059567,395.846465,721.948784,940.057049,831.002916
2023-07-04,4360.700195,1820.449951,2387.699951,946.000000,741.700012,770.599976,432.700012,5109.950195,3347.699951,650.150024,...,931.489235,1052.430726,827.585156,940.007941,431.875469,351.961345,391.918407,731.244082,930.425676,830.834879
2023-07-05,4390.600098,1820.800049,2399.149902,948.200012,742.750000,770.000000,432.399994,5077.649902,3374.399902,649.900024,...,922.644520,1087.835997,889.500447,988.668222,424.450852,355.134345,389.792599,729.514911,919.573818,824.544364
2023-07-06,4400.149902,1820.349976,2402.899902,962.200012,740.049988,769.349976,431.500000,5283.049805,3399.399902,648.750000,...,927.113599,1076.133004,913.091805,994.612405,419.992024,362.570043,391.281033,734.566508,916.346686,825.456597
2023-07-07,4399.750000,1791.500000,2379.600098,951.000000,718.700012,759.849976,417.899994,5146.250000,3343.699951,643.250000,...,914.923360,1088.630647,965.837705,1027.234176,409.782073,370.771894,390.276983,734.007108,907.873157,820.940132

In [7]:
winners = pd.DataFrame(columns=['W1','W2','W3','W4','W5','W6','W7','W8','W9','W10'])
loosers = pd.DataFrame(columns=['L1','L2','L3','L4','L5','L6','L7','L8','L9','L10'])

In [14]:
momentum_df.to_csv('momentum1.csv')

In [8]:
# get top 10 maximum values column name in winners
# get colums containing 'Z_Score' in momentum_df
momentum_df = momentum_df.filter(regex='ALL_Z_Score')
for i in momentum_df.index:
    winners.loc[i] = momentum_df.loc[i].nlargest(10).index.tolist()
    loosers.loc[i] = momentum_df.loc[i].nsmallest(10).index.tolist()

In [9]:
winners

,W1,W2,W3,W4,W5,W6,W7,W8,W9,W10
2022-06-15,NESTLEIND.NSALL_Z_Score,BOSCHLTD.NSALL_Z_Score,PGHH.NSALL_Z_Score,MARUTI.NSALL_Z_Score,BAJFINANCE.NSALL_Z_Score,ULTRACEMCO.NSALL_Z_Score,BRITANNIA.NSALL_Z_Score,DRREDDY.NSALL_Z_Score,ABB.NSALL_Z_Score,BAJAJ-AUTO.NSALL_Z_Score
2022-06-16,NESTLEIND.NSALL_Z_Score,BOSCHLTD.NSALL_Z_Score,PGHH.NSALL_Z_Score,MARUTI.NSALL_Z_Score,BAJFINANCE.NSALL_Z_Score,ULTRACEMCO.NSALL_Z_Score,BRITANNIA.NSALL_Z_Score,DRREDDY.NSALL_Z_Score,ATGL.NSALL_Z_Score,ABB.NSALL_Z_Score
2022-06-17,NESTLEIND.NSALL_Z_Score,BOSCHLTD.NSALL_Z_Score,PGHH.NSALL_Z_Score,MARUTI.NSALL_Z_Score,BAJFINANCE.NSALL_Z_Score,ULTRACEMCO.NSALL_Z_Score,BRITANNIA.NSALL_Z_Score,DRREDDY.NSALL_Z_Score,BAJAJ-AUTO.NSALL_Z_Score,ABB.NSALL_Z_Score
2022-06-20,NESTLEIND.NSALL_Z_Score,BOSCHLTD.NSALL_Z_Score,PGHH.NSALL_Z_Score,MARUTI.NSALL_Z_Score,BAJFINANCE.NSALL_Z_Score,ULTRACEMCO.NSALL_Z_Score,BRITANNIA.NSALL_Z_Score,DRREDDY.NSALL_Z_Score,BAJAJ-AUTO.NSALL_Z_Score,ABB.NSALL_Z_Score
2022-06-21,NESTLEIND.NSALL_Z_Score,BOSCHLTD.NSALL_Z_Score,MARUTI.NSALL_Z_Score,PGHH.NSALL_Z_Score,BAJFINANCE.NSALL_Z_Score,ULTRACEMCO.NSALL_Z_Score,BRITANNIA.NSALL_Z_Score,DRREDDY.NSALL_Z_Score,ATGL.NSALL_Z_Score,BAJAJ-AUTO.NSALL_Z_Score
...,...,...,...,...,...,...,...,...,...,...
2023-07-03,NESTLEIND.NSALL_Z_Score,BOSCHLTD.NSALL_Z_Score,PGHH.NSALL_Z_Score,ULTRACEMCO.NSALL_Z_Score,MARUTI.NSALL_Z_Score,BAJFINANCE.NSALL_Z_Score,APOLLOHOSP.NSALL_Z_Score,LTIM.NSALL_Z_Score,TCS.NSALL_Z_Score,DMART.NSALL_Z_Score
2023-07-04,NESTLEIND.NSALL_Z_Score,BOSCHLTD.NSALL_Z_Score,PGHH.NSALL_Z_Score,ULTRACEMCO.NSALL_Z_Score,MARUTI.NSALL_Z_Score,BAJFINANCE.NSALL_Z_Score,APOLLOHOSP.NSALL_Z_Score,LTIM.NSALL_Z_Score,TCS.NSALL_Z_Score,DMART.NSALL_Z_Score
2023-07-05,NESTLEIND.NSALL_Z_Score,PGHH.NSALL_Z_Score,BOSCHLTD.NSALL_Z_Score,MARUTI.NSALL_Z_Score,ULTRACEMCO.NSALL_Z_Score,BAJFINANCE.NSALL_Z_Score,APOLLOHOSP.NSALL_Z_Score,LTIM.NSALL_Z_Score,TCS.NSALL_Z_Score,DMART.NSALL_Z_Score
2023-07-06,PGHH.NSALL_Z_Score,BOSCHLTD.NSALL_Z_Score,NESTLEIND.NSALL_Z_Score,MARUTI.NSALL_Z_Score,ULTRACEMCO.NSALL_Z_Score,BAJFINANCE.NSALL_Z_Score,APOLLOHOSP.NSALL_Z_Score,LTIM.NSALL_Z_Score,DMART.NSALL_Z_Score,TCS.NSALL_Z_Score
2023-07-07,BOSCHLTD.NSALL_Z_Score,PGHH.NSALL_Z_Score,NESTLEIND.NSALL_Z_Score,MARUTI.NSALL_Z_Score,ULTRACEMCO.NSALL_Z_Score,BAJFINANCE.NSALL_Z_Score,APOLLOHOSP.NSALL_Z_Score,DMART.NSALL_Z_Score,TCS.NSALL_Z_Score,LTIM.NSALL_Z_Score

In [10]:
loosers

,L1,L2,L3,L4,L5,L6,L7,L8,L9,L10
2022-06-15,MOTHERSON.NSALL_Z_Score,IOC.NSALL_Z_Score,BEL.NSALL_Z_Score,GAIL.NSALL_Z_Score,TATASTEEL.NSALL_Z_Score,BANKBARODA.NSALL_Z_Score,NTPC.NSALL_Z_Score,INDUSTOWER.NSALL_Z_Score,ONGC.NSALL_Z_Score,POWERGRID.NSALL_Z_Score
2022-06-16,MOTHERSON.NSALL_Z_Score,IOC.NSALL_Z_Score,GAIL.NSALL_Z_Score,BEL.NSALL_Z_Score,TATASTEEL.NSALL_Z_Score,BANKBARODA.NSALL_Z_Score,NTPC.NSALL_Z_Score,INDUSTOWER.NSALL_Z_Score,ONGC.NSALL_Z_Score,POWERGRID.NSALL_Z_Score
2022-06-17,MOTHERSON.NSALL_Z_Score,IOC.NSALL_Z_Score,GAIL.NSALL_Z_Score,TATASTEEL.NSALL_Z_Score,BEL.NSALL_Z_Score,BANKBARODA.NSALL_Z_Score,NTPC.NSALL_Z_Score,ONGC.NSALL_Z_Score,INDUSTOWER.NSALL_Z_Score,POWERGRID.NSALL_Z_Score
2022-06-20,MOTHERSON.NSALL_Z_Score,IOC.NSALL_Z_Score,TATASTEEL.NSALL_Z_Score,GAIL.NSALL_Z_Score,BEL.NSALL_Z_Score,BANKBARODA.NSALL_Z_Score,NTPC.NSALL_Z_Score,ONGC.NSALL_Z_Score,INDUSTOWER.NSALL_Z_Score,POWERGRID.NSALL_Z_Score
2022-06-21,MOTHERSON.NSALL_Z_Score,IOC.NSALL_Z_Score,TATASTEEL.NSALL_Z_Score,GAIL.NSALL_Z_Score,BEL.NSALL_Z_Score,BANKBARODA.NSALL_Z_Score,NTPC.NSALL_Z_Score,ONGC.NSALL_Z_Score,INDUSTOWER.NSALL_Z_Score,POWERGRID.NSALL_Z_Score
...,...,...,...,...,...,...,...,...,...,...
2023-07-03,MOTHERSON.NSALL_Z_Score,IOC.NSALL_Z_Score,BEL.NSALL_Z_Score,TATASTEEL.NSALL_Z_Score,GAIL.NSALL_Z_Score,BANKBARODA.NSALL_Z_Score,INDUSTOWER.NSALL_Z_Score,NTPC.NSALL_Z_Score,POWERGRID.NSALL_Z_Score,COALINDIA.NSALL_Z_Score
2023-07-04,MOTHERSON.NSALL_Z_Score,IOC.NSALL_Z_Score,BEL.NSALL_Z_Score,TATASTEEL.NSALL_Z_Score,GAIL.NSALL_Z_Score,INDUSTOWER.NSALL_Z_Score,BANKBARODA.NSALL_Z_Score,NTPC.NSALL_Z_Score,POWERGRID.NSALL_Z_Score,COALINDIA.NSALL_Z_Score
2023-07-05,MOTHERSON.NSALL_Z_Score,IOC.NSALL_Z_Score,BEL.NSALL_Z_Score,TATASTEEL.NSALL_Z_Score,GAIL.NSALL_Z_Score,INDUSTOWER.NSALL_Z_Score,BANKBARODA.NSALL_Z_Score,NTPC.NSALL_Z_Score,POWERGRID.NSALL_Z_Score,COALINDIA.NSALL_Z_Score
2023-07-06,MOTHERSON.NSALL_Z_Score,IOC.NSALL_Z_Score,BEL.NSALL_Z_Score,TATASTEEL.NSALL_Z_Score,GAIL.NSALL_Z_Score,INDUSTOWER.NSALL_Z_Score,BANKBARODA.NSALL_Z_Score,NTPC.NSALL_Z_Score,POWERGRID.NSALL_Z_Score,COALINDIA.NSALL_Z_Score
2023-07-07,MOTHERSON.NSALL_Z_Score,IOC.NSALL_Z_Score,BEL.NSALL_Z_Score,TATASTEEL.NSALL_Z_Score,GAIL.NSALL_Z_Score,INDUSTOWER.NSALL_Z_Score,NTPC.NSALL_Z_Score,BANKBARODA.NSALL_Z_Score,POWERGRID.NSALL_Z_Score,COALINDIA.NSALL_Z_Score

In [11]:
winners.to_csv('winners.csv', index=False)
loosers.to_csv('loosers.csv', index=False)